### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by grizzee** [schildbach/public-transport-enabler#101]
Unknown error message after searching for an connection.  
![screenshot_2016-06-30-22-42-17](https://cloud.githubusercontent.com/assets/20231913/16503975/e0e1db52-3f15-11e6-9b2b-68d201436681.png)

**Comment by grote** [comment]
@schildbach is VVS supposed to work or is it known to be broken?

**Comment by schildbach** [comment]
I pushed a fix for this. There is a second parsing problem that appeared with the VVS at the same time but I don't have a fix for that already.
