### ISSUE TITLE
VGN: platforms missing

### ISSUE THREAD

**Issue by theScrabi** [schildbach/public-transport-enabler#104]
When using the VGN service via [Transportr](https://github.com/grote/Transportr/issues/211#issuecomment-230785324) the platform from where a train starts or arrives is not displayed.

**Comment by schildbach** [comment]
Does the VGN have it when you look at their web page?

**Comment by theScrabi** [comment]
Ow it seems like they don't show the platform either.

**Comment by schildbach** [comment]
Ok thanks. I'm closing this, because I think we cannot do anything in code. Feel free to comment the outcome of your inquiry.

**Comment by theScrabi** [comment]
According the answer they sent me, the lines are only displayed in their live info:

> Hallo Herr Schabesberger,
Gleisangaben erhalten Sie unter http://live.vgn.de/auskunft. 
Das ist unsere Echtzeitauskunft im Beta-Test.
