### ISSUE TITLE
Support France-North-West

### ISSUE THREAD

**Issue by patkan** [schildbach/public-transport-enabler#108]
Hi, I would like to see support for France-North-West (especially Rennes).
There is Navitia-data available as "fr-nw". I have forked this project and started to add fr-nw in https://github.com/patkan/public-transport-enabler/tree/add-fr-nw-provider.
However I am currently stuck at testing, since I applied for a Navitia-account but haven't been activated yet.
If someone has the time and a Navitia-account I would be happy if he or she could verify my live-tests.
I will create a Pull Request as soon as I have managed to test this.

**Comment by grote** [comment]
If you still didn't get an API token, try again. They sometimes seem to loose the requests...

**Comment by patkan** [comment]
Thank you that's good to know. I am for a few days on the road and will try afterwards.

**Comment by schildbach** [comment]
Fixed in #110.
