### ISSUE TITLE
San Francisco broken

### ISSUE THREAD

**Issue by boconnell** [schildbach/public-transport-enabler#119]
Copy of https://github.com/grote/Transportr/issues/261

Steps to repro:
Choose San Francisco Bay Area as network in Settings
Try to navigate between 2 points within SF proper (for example from 37.7789/-122.43 to 47.7775/-122.41)
Observe error toast:
![error toast](https://cloud.githubusercontent.com/assets/2806089/20446420/507a0ba6-ad8e-11e6-8813-fc7947e4b250.png)

**Comment by schildbach** [comment]
511.org has stopped using EFA. So I just removed SfProvider.java etc.
