### ISSUE TITLE
Error: NullPointerException

### ISSUE THREAD

**Issue by tenminutemail** [schildbach/public-transport-enabler#121]
Hi there,

Navitia published a lot of [new GTFS datasets for Spain](https://groups.google.com/forum/#!topic/navitia/AhgKV4Isza8). Navitia playground contains a complete list of all datasets now available.

- I tried the new datasets in Navitia playground and all of them work fine.
- In Transportr however, some cities work, others don't or only partially (which is the case of Barcelona and Madrid). I get this error message: "NullPointerException: Attempt to invoke virtual method 'int.de.schildbach.pte.d-to.Product.ordinal()' on a null object reference". I'd like to make the app run again for these cities.

I suppose this error is related to this public-transport-enabler, but I don't know any code, so help would be appreciated.

Thanks!

**Comment by grote** [comment]
In this case, it is a Transportr-only issue due to a provider that hasn't been upstreamed, yet.

**Comment by grote** [comment]
See: grote/Transportr#264
