### ISSUE TITLE
Dubai & ATC (Italy) not working

### ISSUE THREAD

**Issue by tenminutemail** [schildbach/public-transport-enabler#126]
Hi,

I realized that two providers don't work:

- Dubai. Can someone check if it stopped working or if it's only me?

- ATC (Italy) also stopped working. On their homepage, there is some information that this network was integrated into a new one called TPER, they also have some open data available: http://www.tper.it/tper-open-data

grote/transportr#276

**Comment by schildbach** [comment]
Can you post questions on the mailing list? DubProvider works for me. AtcProvider indeed doesn't (for a long time) – should probably be removed.

**Comment by grote** [comment]
Oh there is a mailing list? I couldn't find it and it doesn't seem to be linked from anywhere. Would you mind posting a link to the subscription page?

**Comment by schildbach** [comment]
https://groups.google.com/forum/#!forum/public-transport-enabler-discuss
