### ISSUE TITLE
Rvv Api implementation 

### ISSUE THREAD

**Issue by marsteini** [schildbach/public-transport-enabler#131]
The Regensburger Verkehrsverbund (RVV) has launched a new app with a better support for the whole region around Regensburg (it can show delays as well).
I've checked out the api and I'd like to contribute to this repo, but I'm not sure which provider is the best to implement -  Hafas, Efa or NetworkProvider?

Where exactly are the differences?

**Comment by schildbach** [comment]
It's best to discuss such questions on the [public-transport-enabler-discuss](https://groups.google.com/forum/#!forum/public-transport-enabler-discuss) list.

Hafas is only for the Hafas (Hacon) API. EFA is only for the EFA (Mentz DV) API. NetworkProvider is the generic interface that all must implement. If you post to the list the findings so far – maybe an example call – I can likely identify what type of API this is.
