### ISSUE TITLE
Add Central New York, USA provider

### ISSUE THREAD

**Issue by jnytucep** [schildbach/public-transport-enabler#134]
[Centro](https://en.wikipedia.org/wiki/Central_New_York_Regional_Transportation_Authority) GTFS file can be found at http://www.centro.org/CentroGTFS/CentroGTFS.zip

It appears as though a Google account is needed to submit it to Navitia?

**Comment by patkan** [comment]
You seem to have found their mailing list. You can just post on that like on any regular mailing list (by writing to navitia@googlegroups.com). No need for a Google-account. As long as this data is not in there there is not much to do here.

**Comment by jnytucep** [comment]
It should appear soon in the database.

https://navitia.opendatasoft.com/explore/dataset/us-ny/table/

**Comment by grote** [comment]
This would be closed by #97.
