### ISSUE TITLE
Add delay times to Sydney

### ISSUE THREAD

**Issue by megaminxwin** [schildbach/public-transport-enabler#135]
So I want to use the Transportr app on Android, which uses this code. It's nearly perfect, however I can't help noticing that delays for Sydney aren't currently available. This is rather irritating, since it means that I have to use TripView for the time being - not a bad app, but closed-source.

Apparently this is who I ask for Sydney delay times, so if you could add those, that would be greatly appreciated. Thanks!

**Comment by schildbach** [comment]
Are realtime departures available on the website of Transport for NSW? If so, we should be able to make them available via their EFA adapter.

**Comment by megaminxwin** [comment]
Not on the website itself, it seems; but realtime departures do exist (see: these apps http://www.transportnsw.info/en/travelling-with-us/keep-updated/apps/real-time-transport.page) so one can only assume they have an API...

On 30 January 2017 11:58:18 PM AEDT, Andreas Schildbach <notifications@github.com> wrote:
>Are realtime departures available on the website of Transport for NSW?
>If so, we should be able to make them available via their EFA adapter.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by grote** [comment]
@megaminxwin the point is that adding them would be quick and easy if they were on the website. If they are only available with some other non-EFA API, you would need to implement an entirely new API which is lots of work.

**Comment by megaminxwin** [comment]
Ah, I see. Is it something like this? https://opendata.transport.nsw.gov.au/dataset/public-transport-timetables-realtime

Sorry if it isn't, I'm not a developer so I really don't know...

On 31 January 2017 12:12:32 AM AEDT, Torsten Grote <notifications@github.com> wrote:
>@megaminxwin the point is that adding them would be quick and easy if
>they were on the website. If they are only available with some other
>non-EFA API, you would need to implement an entirely new API which is
>lots of work.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SkyWheel** [comment]
Hi gents.
Any updates on the feature request?
Like @megaminxmin I'm highly interested in realtime information from NSW transport.
Thank you in advance!

**Comment by SkyWheel** [comment]
I think this could be closed as realtime info is available for Sydney since last year.

**Comment by schildbach** [comment]
@SkyWheel Is it available in the EFA (accessible through SydneyProvider)?

**Comment by pserwylo** [comment]
I was in Sydney in January, and was using Transportr with an up to date version of PTE. If I recall correctly, the EFA provider did support delay information (as well as very detailed route geometry). The Australia Navitia provider I contributed was far less detailed by comparison. 

At some point, I'd still love to limit the Navitia provider to work on a per-city basis, rather than all of Australia. If that was done, then we may as well exclude Sydney entirely from the Navitia provider because the EFA one is superior in almost every way. 

On 14 May 2018 8:35:52 am AEST, Andreas Schildbach <notifications@github.com> wrote:
>@SkyWheel Is it available in the EFA (accessible through
>SydneyProvider)?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/schildbach/public-transport-enabler/issues/135#issuecomment-388660900

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by schildbach** [comment]
Ok thanks. So I'll close this then.

Excluding cities would need to be done on the providers side.
