### ISSUE TITLE
Add TRAM Physical Mode on Navitia Provider

### ISSUE THREAD

**Issue by jamescr** [schildbach/public-transport-enabler#144]
I'm testing the public-transport-enabler with my own navitia server[0] and with a very simple GTFS[1] generated with osm2gtfs script that uses the transitfeed library . The value for the route_type for my data is 0 (zero), used for  "Tram, Streetcar, Light rail. Any light rail or street level system within a metropolitan area.". When navitia imports the GTFS that "0" is interpreted as "physical_mode=TRAM" [3]. 

so when i test my Costa Rica Provider (extends Navitia Provider) i got an exception because the physical mode TRAM is not included in the enum PhysicalMode of the AbstractNavitiaProvider.java.

I could upload a PR  for this.

[0] http://navitia.tec.siua.ac.cr/v1/
[1] http://ic-itcr.ac.cr/~jgutierrez/incofer/cr-incofer_feb.zip
[2] https://developers.google.com/transit/gtfs/reference/routes-file
[3] https://github.com/CanalTP/navitia/pull/1382/commits/bdfb257da523ed1c371559beb658117d37e237c6

**Comment by schildbach** [comment]
Fixed by #145.
