### ISSUE TITLE
numChanges of Trips null in AbstractHafasMobileProvider

### ISSUE THREAD

**Issue by patkan** [schildbach/public-transport-enabler#151]
Over at Transportr we have an issue with the returned trips from provider that are based on `AbstractHafasMobileProvider`. The member `numChanges` of the returned trips is `null`. Please see grote/Transportr#316 for reference. I tried to summarize my findings in [this post](https://github.com/grote/Transportr/issues/316#issuecomment-283808598).

May the value `numChanges` be `null`? If yes, could you maybe annotate the `Trip`-class accordingly? In this case we have to adapt the code of Transportr of course.

Is the number of changes not available in the new API or why is this value set to `null`?

**Comment by schildbach** [comment]
I think it's not available as a field in the JSON result. We could probably derive it ourselves.

**Comment by patkan** [comment]
What do you think @schildbach? May `numChanges ` be `null`?
We should probably always be able to provide a value for this, if not directly, then through computation.

**Comment by schildbach** [comment]
We could leave the field as is (nullable) and add a method getNumChanges() which returns the field if not null or tries to derive it from the trip data if not null. However in the end it still might be null, e.g. for trips that only consist of a footpath.
