### ISSUE TITLE
Data for NSW is broken since website change

### ISSUE THREAD

**Issue by SirClutch** [schildbach/public-transport-enabler#156]
Seems like API has changed recently as I'm not able to get any results for my queries.

It seems like the generated URL for the queries are in a different format.
This is an updated query from Town Hall to Parliament House as per: https://www.transportnsw.info
https://www.transportnsw.info/trip/#/?from=10101101&to=poiID:24487:95301001:-1:Parliament%20House%20New%20South%20Wales:Sydney:Parliament%20House%20New%20South%20Wales:ANY:POI:4889750:3755444:GDAV:nsw&accessible=false&wSpeed=4&wDuration=20&itMode=walk&routeFilter=time&train&bus&ferry&lightRail&coach&schoolBus=false&arrDep=dep

Does something like this help? Unfortunately I'm not very well versed in the technical stuff.
https://opendata.transport.nsw.gov.au/node/332/exploreapi

Thanks!

**Comment by SirClutch** [comment]
https://github.com/schildbach/public-transport-enabler/commit/bd69ba7ba96d358524bcf549d0583db8ab51a573

Fixed this!

**Comment by schildbach** [comment]
bd69ba7ba96d358524bcf549d0583db8ab51a573 should fix this a couple of days ago. Can you try updating to latest master?
