### ISSUE TITLE
KvvProvider XML_COORD_REQUEST by lat + lon stopped working

### ISSUE THREAD

**Issue by nickbw2003** [schildbach/public-transport-enabler#158]
Hi there,

first of all thank you for the great project. It helped me a lot ! Sadly the XML_COORD_REQUEST by lat + lon stopped working yesterday for the KvvProvider and I was wondering why. I tried to alter different values of query params but nothing was working. Does someone know what's going on and could help me out with that?

Many thanks
Dennis

**Comment by schildbach** [comment]
Can you post questions to the mailing list please? The problem with KVV seems to be on their end. The coord request now returns an empty result. If the problem persists we should perhaps ask them.

**Comment by nickbw2003** [comment]
Thanks for your reply. Could you give me further information regarding the mailing list / how to post?

**Comment by schildbach** [comment]
The mailing list is a google group: https://groups.google.com/forum/#!forum/public-transport-enabler-discuss
You can either post by their web interface or use it like a regular mailing list.
