### ISSUE TITLE
Norway: Wrong Base URL in NriProvider.

### ISSUE THREAD

**Issue by snake66** [schildbach/public-transport-enabler#159]
The URL used by NriProvider (http://hafas.websrv05.reiseinfo.no/bin/dev/nri/) is no longer valid. The service has been moved to another URL (http://apiprod.reiseinfo.no/bin/rest.exe/v1.1/) Just switching the Base URL should work according to Entur which has taken over responsibility for this service.

**Comment by schildbach** [comment]
Tried switching over the base URL doesn't work, it requires some form of authentication. Can you link the statement from Entur?

**Comment by snake66** [comment]
I asked them by email, and they gave me the new url and say to use the same auth_key as previously. Perhaps the old service worked without an auth_key and the new one don't?

They do have a [form](http://labs.rutebok.no/aapent_api.aspx) for registering as users of the API that will give you the auth key and some more information. They will also keep you posted on further changes in the API and service. (They warn that there will be further/bigger changes coming.)

Not sure how you prefer to go about these things, if each user of the library should get their own auth_keys or you want to provide them as part of the library. In any case, I'll be happy to assist in keeping this provider up to date. (I rely on the info myself.)

**Comment by schildbach** [comment]
I suspect the API they are replacing is not the one public-transport-enabler is/was using. But anyway, if you register maybe you can post a link to their API description so we can have a look.

There are a couple of providers that already require some form of authorization, e.g. all Navitia providers. Have a look at AbstractNavitiaProvider, we could handle it in a similar manner. Basically, the app owner register their apps separately.

**Comment by snake66** [comment]
Seems like a sensible approach, I'll register and see where that leads. An alternative may be to use the Ruter API as mentioned in #150. Seems like it does not require authorization (for now at least.)

**Comment by snake66** [comment]
Their registration form didn't work. I've contacted them by email again.

**Comment by BredeD** [comment]
Hi, 
Here is an example URL. You can use the combination /vs_restapi/ and authKey below.
http://apiprod.reiseinfo.no/bin/rest.exe/v1.1/vs_restapi/trip?authKey=api-test&originId=761023999&destId=761008829

I think this should work. Remove other traces of old 'vs_' and authKey.
Best regards
Brede / Entur as

**Comment by schildbach** [comment]
Ok that API is currently not supported by PTE. The XSD for querying trips is available here: http://apiprod.reiseinfo.no/bin//rest.exe/vs_restapi/v1.1/xsd?name=hafasRestTrip.xsd

Are there also API endpoints for querying departures, nearby stations (to a given coordinate), and autocomplete stations by name?

**Comment by BredeD** [comment]
Yes, try this:
Location: http://apiprod.reiseinfo.no/bin/rest.exe/v1.1/vs_restapi/location?authKey=api-test&input=sola
Location nearbystops: http://apiprod.reiseinfo.no/bin/rest.exe/v1.1/vs_restapi/location.nearbystops?authKey=api-test&originCoordLat=59.006&originCoordLong=5.599&
 
http://apiprod.reiseinfo.no/bin/rest.exe/vs_restapi/v1.1/xsd?name=hafasRestLocation.xsd

**Comment by BredeD** [comment]
@schildbach, attached documentation doesn't fit example URL. Example URL is version Hafas ReST 1.4. Sorry for that. 
If you use v 1.21, you need a new access key.

**Comment by snake66** [comment]
So the url says it's version 1.1 but it's really version 1.4?

Busy with work right now, but will try to get time to look at it over the weekend.

**Comment by BredeD** [comment]
Sorry for the late respond, here is the documetation for the version you use.
http://labs.rutebok.no/media/22639/hafas_rest_interface_nri_v.1.4.1.pdf.
If it runned well before, the only change needed is the base of the URL and add authKey=api-test together with /vs_restapi/. 

Entur has now realeased the new APIs we are developing. Plan is to go live with it during summer / autumn. You can read about it here: [dev.rutebanken.org](http://dev.rutebanken.org) or https://sites.google.com/view/entur/. You should prepare for this, but it is not good enough for production at the moment.

**Comment by snake66** [comment]
Thanks, I have been way too busy to look into this yet too, but hope I can try it out this weekend...

**Comment by snake66** [comment]
Ok, some progress. Six out of the seven tests in NriProviderLiveTest passes, but the short trips test fail. I suspect this is because the ID's for the stations has changed. I'm waiting for information on the new id's.

**Comment by schildbach** [comment]
I just looked at this again, and found out they have an mgate.exe running under their domain: http://apiprod.reiseinfo.no/bin/mgate.exe

This means we theoretically could use an AbstractHafasMobileProvider subclass for this. Unfortunately we'd need to know the authorization for this endpoint, along with the API version and the client ID.

**Comment by BredeD** [comment]
Hi, Please start to use data fra [dev.entur.org](https://dev.entur.org).
We will stop the old NRI-datafeed in end of January.

Best regards, Brede Dammen, Product owner, Entur

**Comment by schildbach** [comment]
@BredeD Thanks. Does this mean you will not use Hafas any more?

**Comment by BredeD** [comment]
We now use and develop around OTP. We will improve it with NeTEx-based OTP instead of GTFS-based in start of January.

**Comment by grote** [comment]
Some background info on that technology:
* https://en.wikipedia.org/wiki/NeTEx
* http://netex-cen.eu/?page_id=462

**Comment by schildbach** [comment]
Sadly I had to remove NRI (Norway) from PTE. The provider stopped working and so far there is no implementation of OTP.

If someone wants to bring it back, feel welcome!

**Comment by BredeD** [comment]
Hi @schildback,
There is new dataset of Norwegian data on both NeTEx, GTFS and OTP-api. Documented at entur.org/dev.

The NRI dataset was removed over a year ago.
Best regards
Brede

**Comment by schildbach** [comment]
Not sure what NeTEx is. PTE cannot use GTFS, as GTFS doesn't provide routing (it's raw data). PTE has no provider for OTP yet, although it probably could.

Transportr is using Navitia for Norway now, probably I'll do the same.

**Comment by BredeD** [comment]
I couldn't search for routes in Norway in Transportr app. Look like the old NRI dataset there too.

**Comment by BredeD** [comment]
NeTEx is a rich raw data format. It is an EU standard, coming up as an mandatory format in EU end of next year. Our OTP is now based on NeTEx, which means it is richer than the previos GTFS based OTP. What is PTE?

**Comment by schildbach** [comment]
PTE stands for public-transport-enabler, which is the project this issue was opened on.

**Comment by Spass1966** [comment]
What's the status of this?

**Comment by BredeD** [comment]
We made a Norwegian profile, which is now a Nordic profile. Denmark, Sweden and Finland are developing a NeTEx file export based on the Nordic profile. This means, in short time the nordics can be enhanced with richer data in the same format and profile. We will provide GTFS also as a substitute format, which will work well in some usecases. 
In Europe there is also a French profile, and there has been etablished an European profile. There is minor differences in the profile. 
Do you plan to develop for the NeTEx dataset?
