### ISSUE TITLE
9292 redirect exception (NL)

### ISSUE THREAD

**Issue by nicorikken** [schildbach/public-transport-enabler#163]
The Dutch 9292 provider stopped working since a couple of days. The UI of transportr displays a UnexpectedRedirectException https://api.9292.nl/0.1/journeys?lang=nl-NL&...

Near daily Transportr user here, so thanks for getting this initial support. Hope to get it working again soon.

**Comment by nicorikken** [comment]
Situation screenshot:
![2017-06-14 11 08 07](https://user-images.githubusercontent.com/7458098/27124753-4f72f2f6-50f2-11e7-8e8d-478051a368a5.jpg)

**Comment by grote** [comment]
@full-duplex you are maintaining this provider. Do you know what is going on?

**Comment by full-duplex** [comment]
@nicorikken Does it always give that error?

I had a quick look and it seems like they randomly send a 301 redirect to some 404 not found page, but I couldn't reliably reproduce this, even for requests to identical URLs. I'll try to have a better look at it later this week.

**Comment by nicorikken** [comment]
I checked today, and it works again. Something with their infrastructure maybe? Unless this needs further analysis, this can be closed. Thanks for looking into this.

**Comment by schildbach** [comment]
Thanks for tracking this.

**Comment by TheLastProject** [comment]
I've been getting this on-and-off for the past few days, but when I do I get it rather consistently for a while. Yet at other times it works fine. Probably something on their side.
