### ISSUE TITLE
api.reittiopas.fi will shut down

### ISSUE THREAD

**Issue by schildbach** [schildbach/public-transport-enabler#166]
Just got this mail from HSL:

> Dear HSL data user,
>
> The old HSL Journey Planner (classic.reittiopas.fi) will be discontinued at the end of November, causing changes for API users, too. HSL will continue to develop open data and open APIs. We hope that the transition to the new APIs will not cause you any issues and you will still be able to utilize the APIs for your needs.
>
> The following changes will take place in the autumn:
>
> 1\.      GTFS zip file will be relocated on 31 August 2017. The obsolete address is http://api.reittiopas.fi/data/google_transit.zip
> The new address is https://api.digitransit.fi/routing-data/v2/hsl/HSL.zip
>
> 2\.      The old Classic Journey Planner will be discontinued by the end of November and at the same time the routing API (http://api.reittiopas.fi/hsl/prod) and other outdated APIs will be run down.
>
> \-        Instructions and addresses for the new APIs can be found here: https://www.hsl.fi/en/node/10460 , partly in English.
>
> \-        We recommend you to start using the new API as soon as possible to enable us to respond to any development needs in the operation of the API.
>
> In case you have any problems, please send us a message on Facebook, Gitter or Twitter
>
> \-        Facebook https://www.facebook.com/HSLdevcom/  
>
> \-        Gitter https://gitter.im/HSLdevcom
>
> \-        Twitter https://twitter.com/HSLdevcom
>
> 
>
> With kind regards,
>
>Antero Karppinen and the Journey Planner development team

@msjoberg

**Comment by msjoberg** [comment]
Yes, I also got the same email. Unfortunately I have very little free time at the moment, so it is unlikely I will have time to update to the new API :-( I wonder if there are any other ways to include HSL support...

**Comment by schildbach** [comment]
We're now using Navitia for the Finland region.
