### ISSUE TITLE
Live times for VGS (Saarland, Germany) stopped working

### ISSUE THREAD

**Issue by RalfJung** [schildbach/public-transport-enabler#168]
Live delay updates and canceled buses stopped working for the VGS transport system in Saarland, Germany. This used to work fine at the beginning of the year, so probably something changed on their side? No idea how to even debug this.

This is using Transportr 1.1.8 installed via F-Droid.

Cc https://github.com/grote/Transportr/issues/363

**Comment by schildbach** [comment]
Have you tried on their website at https://www.saarfahrplan.de/cgi-bin/ if you can see live data there?

**Comment by RalfJung** [comment]
Yes, both their Website and their app have working live data. (The website is at http://www.saarfahrplan.de/, no HTTPS.)

**Comment by RalfJung** [comment]
Hm, actually, right now, Transportr *also* has working live data. At least for the next two connections I checked; later connections have "on time" on the website but show nothing (i.e., no green "+0") in Transportr.

But a week ago, there definitely was a case of a bus being cancelled, and that being reported in their app, but not in Transportr. (I know because I ended up waiting for it...) Maybe this only affects "bus cancelled", but not delays?

**Comment by grote** [comment]
> (i.e., no green "+0") in Transportr.

I think Transportr doesn't show +0 if there's no delay. Does it?

> Maybe this only affects "bus cancelled", but not delays?

Transportr does not yet show canceled buses. I didn't look into how PTE indicates a canceled connection. At first, I assumed it wouldn't return connections that are canceled anyway.

**Comment by RalfJung** [comment]
> I think Transportr doesn't show +0 if there's no delay. Does it?

Oh. Well but then how is the user supposed to distinguish "no data for this bus" and "on time"?

> At first, I assumed it wouldn't return connections that are canceled anyway.

This doesn't just affect connections, but also e.g. "next departures".

**Comment by ialokim** [comment]
> At first, I assumed it wouldn't return connections that are canceled anyway.

That's true for now, but I think this something that should be changed. See #102 for a first try and (hopefully) a discussion about this topic.

**Comment by ialokim** [comment]
This may safely be closed @schildbach :slightly_smiling_face: :
