### ISSUE TITLE
ParisProvider: queryTrips returns only 1 trip

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#18]
I queried a couple of trips and there's usually only one trip returned while all the other providers return at least 3 trips.

Also, querying for earlier or later trips does not work for me, at least not the same way it does for other providers.

This is probably for @aelkhour.

**Comment by aelkhour** [comment]
@schildbach I had set the requested trip count to 1 for testing purposes, but I realised that now navitia returns only one trip unless specified otherwise. Should I take the default trip count for the navitia provider, or hardcode some value?

**Comment by schildbach** [comment]
AbstractNetworkProvider has the "numTripsRequested" property. That's the value you should use. Currently the default is set to 6. If Navitia for some reason should have a lower default, it might make sense to refactor the code to allow the service provider pick a default.

**Comment by aelkhour** [comment]
@grote Could you retest please?

**Comment by grote** [comment]
I'm getting 6 trips now like expected. Thanks for the fix!
