### ISSUE TITLE
Add VRT (Trier, Germany) Provider

### ISSUE THREAD

**Issue by JayVii** [schildbach/public-transport-enabler#182]
The data has to be requested via mail, but will be provided for free ([open license](https://www.govdata.de/dl-de/by-2-0)):
https://www.vrt-info.de/opendata

* * *

*Edit: More info*
https://www.vrt-info.de/openservice
*Here they only talk about the VDV. Hm...*

* * *

They provide a VDV Format, which apparently is unsuitable because it doesn't update on a daily basis, but sessional.
They **also** provide a TRIAS format, which does update on a daily basis and would be most suitable in this case.

I would be more than happy, if this could be implemented.
Thank you very much

**Comment by schildbach** [comment]
Public-transport-enabler is not meant for processing the raw data itself. It relies on an API (e.g. for routing), like EFA, Hafas or Navitia.

**Comment by grote** [comment]
https://www.vrt-info.de/openservice
> Als Zugang setzt der VRT eine neue, neutrale Schnittstelle ein, die auch von anderen Betreibern von Auskunftssystemen angeboten wird. Das Format dieser Schnittstelle ist vom Verband Deutscher Verkehrsunternehmen (VDV) in der VDV Schrift Nr. 431- 2 dokumentiert. Diese Schnittstelle ersetzt die vorhandene EFA-API, die 2017 abgeschaltet wird.

And this like to [Internet Protokoll basierte Kommunikationsdienste im ÖV - Das Projekt "IP-KOM-ÖV"](https://www.vdv.de/ip-kom-oev.aspx)

**Comment by JayVii** [comment]
On [vrt-info.de](https://www.vrt-info.de/openservice) it says:

> Der Verkehrsverbund Region Trier GmbH (VRT) hat den Verkehrsverbund Rhein-Neckar GmbH (VRN) mit der Bereitstellung der Daten beauftragt.

And indeed, VRN does provide the data for the area covered by the VRT. Thus, I'm closing this issue.
