### ISSUE TITLE
efa.ivb.at (Innsbruck/IVB): API gone (404)

### ISSUE THREAD

**Issue by girst** [schildbach/public-transport-enabler#183]
The IVB API has been removed; any requests to `https://efa.ivb.at/ivb/` are redirected to a 404 page (and the subdomain itself now returns the homepage). 

The new web interface for trip requests is at `https://fahrplan.ivb.at`, but I don't think a public API documentation is available; the usual paths (`/ivb/XSLT_TRIP_REQUEST2` etc.) don't exist there any more.

**Comment by girst** [comment]
just poking around a bit: requests seem to be handled by `/bin/mgate.exe` -- a quick google search returns entries about DB's HAFAS system; maybe this API can be adapted (although I personally lack the know how about android programming)

**Comment by schildbach** [comment]
Public-transport-enabler is a standard Java library – no Android involved. If this is Hafas we can likely talk to it.

**Comment by schildbach** [comment]
I removed IvbProvider via ea0865f3c236a70ff20196378454e0ccd394a895 as their EFA API is gone forever. I think it's safe to assume VvtProvider can be used in place as that one covers Tyrol (which Innsbruck belongs to).

**Comment by simon04** [comment]
`VvtProvider` is disabled in Öffi "because the VVT explicitly desires not to be included in Öffi". :disappointed:

**Comment by schildbach** [comment]
@simon04 Yes, sadly.
