### ISSUE TITLE
HAFAS mobile API 1.16: find out how the mic & mac parameters work

### ISSUE THREAD

**Issue by derhuerst** [schildbach/public-transport-enabler#187]
[this is a cross-post from derhuerst/hafas-client#3]

[The VBB endpoint now has a `1.16` API version, which provides more detailed responses.](https://gist.github.com/derhuerst/bf3caf8685b69c44f16f073402a59e32) Also, older versions might be shut off in the future.

There are to query parameters `mic` & `mac` though, which seem to be necessary to get data. I haven't figured out how they work. It might be similar to [the way *Deutsche Bahn* does it](https://github.com/derhuerst/hafas-client/blob/cea043e44f3aff06c4f4ed245012e719e6227e7f/p/db/index.js#L26-L35).

Maybe someone from the community of this project knows what they are and how they work?

**Comment by alexander-albers** [comment]
I came across the same issue a few weeks ago: `mic = MD5(requestString)`, `mac = MD5(mic + salt)`. Same as with the `checksum` parameter, both md5 hashes need to be in hex representation.
I hope that helps. :)

**Comment by derhuerst** [comment]
But what is the `salt`? Does someone know? 😉

**Comment by alexander-albers** [comment]
Yeah, that's a little trickier. ;)

First, you need to find the `HCI_CHECKSUM`, usually located in `haf_config_base.properties`. Then, you need to "decrypt" the checksum as done here: [https://pastebin.com/4RAmgbF8](https://pastebin.com/4RAmgbF8). The result can be then used as the hash value. :)

**Comment by derhuerst** [comment]
thanks for you help. i don't have all puzzle pieces together though.

- Is the encrypted checksum (`HCI_CHECKSUM`) stored in the config file as base64 or plain text?
- I haven't found out what the `PKCS5Padding` part of the cipher exactly means and how to implement it in other languages.
- Did you mean that the decrypted checksum can be used as a *salt*?

**Comment by alexander-albers** [comment]
- Correct, the checksum is stored as base64.
- You only need to decrypt the checksum once. You can run the Java snippet (which also decodes the base64 hci) and just use the result in your preferred language.
- Yes, the decrypted checksum is what I referred to as salt and can be used for the `mac` parameter.

**Comment by derhuerst** [comment]
Thanks! For the record, some references I found while digging around:

- https://docs.oracle.com/javase/7/docs/api/javax/crypto/Cipher.html

**Comment by derhuerst** [comment]
@alexander-albers On last request. In order to reduce the number of error sources, could you give me an example encrypted checksum/salt pair?

I've found [this encrypted checksum for Deutsche Bahn](https://gist.github.com/anonymous/d3323a5d2d6e159ed42b12afd0380434#file-haf_config_base-properties-L82): `rGhXPq+xAlvJd8T8cMnojdD0IoaOY53X7DPAbcXYe5g=`.

I have the following salt as the result: `a0a18e5cdced2d697afe46aef5097ec269ce1ab8e73e1effbf769e866ef71ebc`.

**Comment by alexander-albers** [comment]
The encrypted checksum is correct, but the salt would be `bdI8UVj40K5fvxwf`.

`System.out.println(decrypt("rGhXPq+xAlvJd8T8cMnojdD0IoaOY53X7DPAbcXYe5g=".getBytes(StandardCharsets.UTF_8)));`

**Comment by derhuerst** [comment]
[Finally got it working.](https://gist.github.com/derhuerst/81a7d6a7298c16c3c68e6d54fd80755f)

**Comment by schildbach** [comment]
@alexander-albers Thanks for this valuable info.

@derhuerst Do you plan to submit a PR for Hafas 1.16 support? It would be a nice feature to have!

**Comment by derhuerst** [comment]
@schildbach I don't I'm proficient enough in Java. I haven't implemented the 1.16 protocol in my JS client yet, but once I did, I may either submit a PR or at least provide all the knowledge I have.

**Comment by derhuerst** [comment]
@alexander-albers I need your help again.

[I extracted the encrypted checksum `jvKrxmixHfD58eaNuQU4xcRWamPNQ/VYKfr2STdKvHA=` from the VBB Android app.](https://gist.github.com/derhuerst/a8d94a433358abc015ff77df4481070c#file-haf_config_base-properties-L39) With [my tool](https://runkit.com/derhuerst/hafas-decrypt-encrypted-mac-salt) based on your code, I decrypted the following salt:

`5243544a4d3266467846667878516649` – hex
`RCTJM2fFxFfxxQfI ` – utf8

[A recorded request from the latest VBB Android app](https://gist.github.com/derhuerst/d317fd20c70ef880de670995f6602892#file-journey-details-http):

```http
POST /bin/mgate.exe?mac=f1de7eace70370b8613359f9dc2b81bc&mic=b5d1f2fd4c9de9764e04f93c135af4b1 HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; SHIFT5.1 Build/LMY47I)
Content-Type: application/json;charset=UTF-8
Host: fahrinfo.vbb.de
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 376

{"auth":{"aid":"hafas-vbb-apps","type":"AID"},"client":{"id":"VBB","name":"Bus & Bahn ","os":"Android 5.1","res":"720x1216","type":"AND","ua":"Dalvik/2.1.0 (Linux; U; Android 5.1; SHIFT5.1 Build/LMY47I)","v":1000029},"ext":"VBB.1","formatted":false,"lang":"deu","svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"JourneyDetails","req":{"jid":"1|28233|20|86|21022018"}}],"ver":"1.16"}
```

I calculated the `mic` correctly (`b5d1f2fd4c9de9764e04f93c135af4b1 `), but the `mac` doesn't match (I got `3edc9c3b1a166c983de78668d403fc2b`).

I assume the key for decrypting the salt is different for VBB apps. Or did I miss something?

**Comment by alexander-albers** [comment]
Hi! The key seems correct to me. How did you calculate the `mac` parameter? You need to perform `md5(md5(requestString) + salt)`. Both md5 functions need to return a hex value, and the salt needs to be in utf8 representation.

**Comment by derhuerst** [comment]
Node crypto doesn't work with strings, but with binary data directly. Therefore it doesn't matter if I had specified the salt as hex or utf8 before. My code works with the example we discussed before.

**Comment by derhuerst** [comment]
What's you `mac` result, given the encrypted salt and request string above?

**Comment by alexander-albers** [comment]
I’m not sure how strings work in Node, but in Java it does make a difference when you concartenate two utf strings instead of two hex strings. Try to convert the first result to a hex string first and combine that one with the hex representation of your salt. Then, you can encode the resulting string to binary again and use if for the second md5 function.

**Comment by derhuerst** [comment]
Would you mind trying to reproduce this with Java? If you don't get the correct `mac` either, the `salt` must be wrong.

**Comment by derhuerst** [comment]
@alexander-albers ping (:

**Comment by alexander-albers** [comment]
Did you try to concartenate both hex strings before applying the md5 function?

**Comment by derhuerst** [comment]
As I said, in Node there's no difference between `Buffer.from(str1 + str2, 'utf8')` and `Buffer.concat([Buffer.from(str1, 'utf8'), Buffer.from(str2, 'utf8')])`.

**Comment by alexander-albers** [comment]
I get that, but are you using the _hex_ representation of both the md5-encoded request string and the salt?

**Comment by derhuerst** [comment]
No, I use the *binary* representation for hashing:

```js
const md5 = buf => require('crypto').createHash('md5').update(buf).digest()
const req = Buffer.from('{"auth":{"aid":"hafas-vbb-apps","type":"AID"},"client":{"id":"VBB","name":"Bus & Bahn ","os":"Android 5.1","res":"720x1216","type":"AND","ua":"Dalvik/2.1.0 (Linux; U; Android 5.1; SHIFT5.1 Build/LMY47I)","v":1000029},"ext":"VBB.1","formatted":false,"lang":"deu","svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"JourneyDetails","req":{"jid":"1|28233|20|86|21022018"}}],"ver":"1.16"}', 'utf8')
const mic = md5(req)
mic.toString('hex') // b5d1f2fd4c9de9764e04f93c135af4b1, matches!
const salt = Buffer.from('5243544a4d3266467846667878516649', 'hex') // decrypted using your code
const mac = md5(Buffer.concat([mic, salt]))
mac.toString('hex') // 3edc9c3b1a166c983de78668d403fc2b, does not match!
```

**Comment by alexander-albers** [comment]
Try the following:
`const mac = md5(Buffer.concat([Buffer.from(mic.toString('hex'), 'utf8'), salt]))`

**Comment by derhuerst** [comment]
Thanks again! I really didn't expect that they would process the MIC differently than the salt. Reading your comments, I thought you were confused about the way of handling crypto in Node.

**Comment by guitar9** [comment]
hi i have another question. I have looked the requests of the Deutsche Bahn app.  I am stucked where to get the array with station informations. There is a checksum. Sombody knows how to calculate the checksum? I want to do this calculation in javascript. But if somebody knows how to calculate it in java i would be nice.
This are example request i tried out.
```
aaaa = af9343ee2b5d0df1bb1c41cc94cb7639
aaab = f041d6c597cd4a8df7e10534fdc00f66
aaac = 6f3f57478e37bd7e6d2e7c2af284162f
aaad = 734a5c3794a160fdc3e9c9d441c9dae3
....
bbbbb = 8ec957faad401f5fe01c1d129646ad2e
```


![image](https://user-images.githubusercontent.com/25721108/40274487-83849f04-5bd7-11e8-8e6e-ea053a3c982f.png)

**Comment by derhuerst** [comment]
@guitar9 

> Sombody knows how to calculate the checksum?

See above. I've implemented this here:

https://github.com/public-transport/hafas-client/blob/48f2cefb5b2b65a5f84f5c499835c3315ab67322/p/db/index.js#L134-L135

https://github.com/public-transport/hafas-client/blob/ef42edbfd7d8384c153b0bf712235eca4eae44c7/lib/request.js#L32-L38

> But if somebody knows how to calculate it in java it would be nice.

See above as well.

**Comment by schildbach** [comment]
I also implemented `mic`/`mac` and merged. See c410fcda65bec1e17ed21601b872b03b5d612d86 and 9fbd1f1864197b03cb6e25554991235894ccd161.

**Comment by schildbach** [comment]
@derhuerst In your [Tool](https://runkit.com/derhuerst/hafas-decrypt-encrypted-mac-salt) above, where does the key `61483646387a527569426e6d33336655` come from?

**Comment by schildbach** [comment]
Likewise, @alexander-albers where did you get the key `97, 72, 54, 70, 56, 122, 82, 117, 105, 66, 110, 109, 51, 51, 102, 85` in your [pastebin](https://pastebin.com/4RAmgbF8) from?

**Comment by alexander-albers** [comment]
@schildbach the key is hardcoded into every app.

**Comment by schildbach** [comment]
@alexander-albers Right, but where? Everything we're talking about here is hardcoded into the app, but the key doesn't appear in `/res/raw/haf_config_base.properties`.

**Comment by alexander-albers** [comment]
@schildbach No, the key is actually hardcoded, it is in the Java-code of the Android app. :P

**Comment by schildbach** [comment]
FWIW:
```
grep -RFl "<title[^>]*>(.*?)</title>"
grep -F -A17 ".array-data" <file>
```
