### ISSUE TITLE
ParisProvider: Unnecessary Walks For Trip Start and End

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#19]
It seems that Trip Results have a 0m/0min walk at the beginning and the end of the trip with the same name as the actual station. If the Navitia API outputs these, maybe they should just be skipped and not returned via PTE? Also, there seems to be an issue with departure and arrival times.
See the screenshot below for an example.

This is probably for @aelkhour.

![footway](https://cloud.githubusercontent.com/assets/244947/5514262/46be5220-888d-11e4-93ed-add4e61ade93.png)

**Comment by aelkhour** [comment]
@grote Could you please test and close if needed?

**Comment by grote** [comment]
Thanks @aelkhour! These are gone now in my tests.
