### ISSUE TITLE
find out how the Saarfahrplan HAFAS protocol works

### ISSUE THREAD

**Issue by derhuerst** [schildbach/public-transport-enabler#191]
I'm currently struggling to reverse-engineer the [Saarfahrplan](http://www.saarfahrplan.de) `mgate.exe` API. I've recorded [a (valid) request](https://gist.github.com/derhuerst/719a41524b257350bd92c455fea1d9b5) for this.

The response format seems to be just gzipped XML (event the the headers don't say so). **I want to find out how the request is encoded.** G(un)zipping unfortunately doesn't work. Maybe it is encrypted?

@alexander-albers Maybe you know more about this, as you already helped me with #187.

*Note*: I'm hijacking this issue tracker in a way, but I think that the public-transport-enabler project might benefit from documented knowledge about this.

**Comment by derhuerst** [comment]
OpendataCH/Transport#105 seems to be related to this.

**Comment by derhuerst** [comment]
@ski7777 has extracted the config files from the Android app: https://gist.github.com/ski7777/0491b0a1153c8e933ddcbc1cdaecaa86

**Comment by schildbach** [comment]
Have you looked at VgsProvider.java? It uses the legacy Hafas API but it still works.

**Comment by ialokim** [comment]
I've looked over the legacy provider briefly. It doesn't query the mgate.exe endpoint, right? An if it does, not in a binary format, right?

> `AbstractHafasLegacyProvider` is indeed using the "old" binary, or even xml format.

**Comment by schildbach** [comment]
I just checked and it has an mgate.exe endpoint. I guess the Saarfahrplan app is using it, assuming it is the usual hafas clone. Someone would need to capture api requests/responses.

**Comment by schildbach** [comment]
@ialokim For querying nearby stations, VgsProvider is even still parsing HTML!

**Comment by ialokim** [comment]
If I remember correctly,  the Android app uses the binary format while the iOS app is using `mgate.exe`, but as @derhuerst pointed out, this mobile endpoint seems to be encrypted. 

> @ialokim For querying nearby stations, VgsProvider is even still parsing HTML! 
Wow, that sounds quite ugly :speak_no_evil:

**Comment by ski7777** [comment]
I have a license to use the extxml.exe . I will provide it as REST interface. If you are interested in using it, feel free to contact me.

Raphael

**Comment by derhuerst** [comment]
@ski7777 Please also provide the source code of any working implementation!

**Comment by ski7777** [comment]
Of course I will do it. I will provide a public available API. Sadly I
can´t provide the Access Token. Also my server infrastructure (Raspberry Pi
3B) is very limited. You can implement it in Oeffi but then we need to
discuss an other server solution.

Raphael

Jannis Redmann <notifications@github.com> schrieb am Di., 31. Juli 2018 um
20:32 Uhr:

**Comment by ski7777** [comment]
I would like to publish it right away but the code is still very very dirty and 2/3 is uncommented...
But in the end my code will be a better documentation of the extxml.exe than the one hacon sent to me.

Raphael

**Comment by ski7777** [comment]
Watch https://github.com/ski7777/saarvv-client/

**Comment by schildbach** [comment]
@ski7777 Thanks. That's the Hafas XML API. Public-transport-enabler has full support for that via the `AbstractHafasLegacyProvider`.

**Comment by derhuerst** [comment]
This is obsolete, now that #246 has been dealt with, right?

**Comment by ialokim** [comment]
> This is obsolete, now that #246 has been dealt with, right?

Should be obsolete and ready to be closed now, right.

**Comment by schildbach** [comment]
Ok, I'll close this.
