### ISSUE TITLE
Add support for VSN (Lower Saxony)

### ISSUE THREAD

**Issue by cosmofelix** [schildbach/public-transport-enabler#203]
Is it possible to support the "Verkehrsverbund Süd-Niedersachen", VSN? [https://www.vsninfo.de/de/home](https://www.vsninfo.de/de/home) 
 
Until a few days ago it was possible to use DB as provider (in Transportr) but apparently they removed local transportation, at least in this area.

**Comment by 1110101** [comment]
It's probably because of the timetable change last sunday 07-15.

**Comment by schildbach** [comment]
They are using Hafas, so it should be possible. However, the region is also covered by GVH (GvhProvider).

**Comment by cosmofelix** [comment]
I tried GVH. It works e.g. for Hannover but not for Göttingen anymore. And NVV (Nordhessischer VerkehrsVerbund) in the south of Göttingen is missing the local transportation there as well.

Please add support for VSN.

**Comment by schildbach** [comment]
I just checked, they're using VBN. Please select "Bremen, Rostock, Osnabrück & South Lower Saxony" for VBN.

**Comment by cosmofelix** [comment]
Thanks for looking into that again. Unfortunately I con not find the VBN network in the transportr app, using version 2.0.2. Is this something I need to report to the grote/transportr?

**Comment by schildbach** [comment]
Yes, please report there.
