### ISSUE TITLE
Add support for Tampere Public Transport

### ISSUE THREAD

**Issue by kusochi** [schildbach/public-transport-enabler#212]
Hello,
I would like to see support for Tampere Public Transport (Finnish: Tampereen joukkoliikenne). I'm not a developer but I was able to find links related to the APIs:
http://developer.publictransport.tampere.fi/pages/en/home.php (apparently requires an account)
http://data.itsfactory.fi/ (seems to be open access to all APIs no account required)

**Comment by grote** [comment]
I think Tampere will be part of #208

https://navitia.opendatasoft.com/explore/dataset/fi/table/?sort=type_file

**Comment by kusochi** [comment]
Oh cool it looks like it will be covering pretty much everything for Finnish public transport then! I will close this issue.
