### ISSUE TITLE
Move most of the parameters for queryTrips in new TripOptions class

### ISSUE THREAD

**Issue by ialokim** [schildbach/public-transport-enabler#214]
This is just a follow up on [#102 (comment)](https://github.com/schildbach/public-transport-enabler/pull/102#issuecomment-407667057) to discuss the idea.

I've had a quick look which of the parameters could be moved into a new `TripOptions` class. I would leave `from`, `to` and `date` as normal parameters, while moving all the others into the new class (`dep`, `products`, `optimize`, `walkSpeed`, `accessibility`, `options`) because they seem quite "auxiliary". Would you be ok with this distribution @schildbach ?

**Comment by schildbach** [comment]
Sounds good to me, except `dep`. It's kind of tied to `date`.

**Comment by ialokim** [comment]
Okay, so we would leave `dep` as normal parameter too (and would have `via` as auxiliary option, which I forgot to mention above)?

**Comment by schildbach** [comment]
I'm a bit indifferent to `via`, but yes. What do others think?

**Comment by grote** [comment]
While I think this change would be an improvement, I don't think it is worth to break the API without a strong argument. Making it prettier isn't a strong argument that would justify the re-factoring required for the consumers of the library. Maybe the old API can continue to exist and get deprecated, but converted to the new format?

> I'm a bit indifferent to via, but yes. What do others think?

I'd leave via out of the options and instead leave it between from and to.

**Comment by schildbach** [comment]
I'm fine with keeping a deprecated old version of the method.

**Comment by ialokim** [comment]
Fixed with #216.
