### ISSUE TITLE
Secrets.java - get an error during compilation.

### ISSUE THREAD

**Issue by vkozubal** [schildbach/public-transport-enabler#22]
Hi!
when I pull  and run mvn clean install i get the following error:
[ERROR] /public-transport-enabler/enabler/test/de/schildbach/pte/live/ParisProviderLiveTest.java:[51,41] cannot find symbol
[ERROR] symbol:   variable Secrets
I saw Secrets.java in .gitignore file and Secrets.java.templete file.
I can't understand how does it work  and what is the purpose. Could you please give me some hint.

Thank you.

**Comment by matey-jack** [comment]
Just rename the template to Secrets.java to get it to compile.
We could put the secrets into a properties file to make fresh checkouts always compilable.

**Comment by schildbach** [comment]
Probably, but then a special solution for Android needs to be implemented because Android doesn't support classpath resources.

**Comment by schildbach** [comment]
Closing this, as the original problem should be solved now (thanks @matey-jack).
