### ISSUE TITLE
Add Support for AVV (Aachener Verkehrsverbund) 

### ISSUE THREAD

**Issue by Anbeku** [schildbach/public-transport-enabler#221]
I really like support for AVV since AVVs own app is very poor and there is no useful alternative. AVV offers an HAFAS-ReST-API that may be used as an OpenService. See http://opendata.avv.de/lizenz_und_readme.txt for further information (in german).

**Comment by Anbeku** [comment]
Probably blocked by https://github.com/schildbach/public-transport-enabler/issues/54

**Comment by schildbach** [comment]
Implemented via eda7d37b838f9e08a85ff3b31bfcd131bbd4050e
