### ISSUE TITLE
PlProvider: unexpected redirect

### ISSUE THREAD

**Issue by gjedeer** [schildbach/public-transport-enabler#223]
I only have a screen shot from Transportr.

![0000000f screenshot_transportr_20180823-080355](https://user-images.githubusercontent.com/315648/44508467-aeae9f00-a6ae-11e8-9b36-126d8fce2bd8.png)

**Comment by grote** [comment]
Looks like they are redirecting from http to https now.

**Comment by mimi89999** [comment]
I will look at it.

**Comment by schildbach** [comment]
Fixed via 9e99ea59d216e2f1ad38263bd7fd4f05a245f56e

**Comment by mimi89999** [comment]
How have you managed to find that Hafas instance?

**Comment by schildbach** [comment]
Can't remember. Probably via pastebin.

**Comment by gjedeer** [comment]
Thank you!
