### ISSUE TITLE
BC navita provider: no PhysicalMode "NA"

### ISSUE THREAD

**Issue by anjandev** [schildbach/public-transport-enabler#224]
![screenshot_transportr_20180912-000845](https://user-images.githubusercontent.com/8602360/45532764-15a10e80-b7aa-11e8-91e3-d85f3a2ea805.png)

**Comment by anjandev** [comment]
![screenshot_transportr_20180912-000845](https://user-images.githubusercontent.com/8602360/45532764-15a10e80-b7aa-11e8-91e3-d85f3a2ea805.png)

**Comment by anjandev** [comment]
I think  I fixed it here:

https://github.com/anjandev/public-transport-enabler/commit/b8ec92de14515d452b8230fe75458c0958d9065e

**Comment by anjandev** [comment]
I made a mistake. I will open a new issue with everything proper. My bad

**Comment by anjandev** [comment]
I investigated this issue. Turns out that when the route includes the skytrain (the overhead subway in vancouver) Navitia returns the "NA" physical mode. 

https://api.navitia.io/v1/coverage/ca-bc/journeys?from=poi%3Aosm%3Anode%3A384252960&to=poi%3Aosm%3Away%3A102254132&

**Comment by schildbach** [comment]
What does "NA" stand for? Maybe "not available" or "not applicable"? If so, then I'd vote for removing the enum value entirely and use "null" instead.

**Comment by anjandev** [comment]
@schildbach in this case, vancouver's skytrain was placed as NA. Should I put it as null? Would that not just remove the physical mode from apps? Ie. When a route requires the skytrain it's just a blank?

**Comment by schildbach** [comment]
Actually I'm not so sure any more. PhysicalMode is used within AbstractNavitiaProvider only, so apps (= users of the library) won't care about it.

@aelkhour once introduced the enum in commit 9f2b3b57e126864ec8de5dc8c7cee29e8606a078, maybe he want to add his view to the discussion?

**Comment by anjandev** [comment]
@schildbach I sent an email to @aelkhour and I have gotten no response. It has been a week. 

What is the purpose of the physical_mode. Like what is it used for? Can we change it to Null?

**Comment by schildbach** [comment]
@prhod This issue about "NA" PhysicalMode in the British Columbia dataset is very similar to #236. What does NA stand for? Is it perhaps an error in the dataset?

**Comment by schildbach** [comment]
I should mention that according to http://doc.navitia.io/#public-transport-objects NA is not valid.

**Comment by grote** [comment]
I think ideally Navitia's data team fixes this at their side and sets the proper physical mode. There should be a QA step in the publishing pipeline that ensures all physical modes are valid.

**Comment by schildbach** [comment]
@grote Agreed.

**Comment by anjandev** [comment]
@grote @schildbach yes, a QA process would be nice because routes with the skytrain were working before and they just stopped working...

**Comment by grote** [comment]
If there's not answer from @prhod, you can also mail them https://groups.google.com/forum/#!forum/navitia It is a separate organization.

**Comment by prhod** [comment]
Hello @grote @schildbach, sorry for the delay of the response ! 
The purpose of the physical_mode is to provide a fixed list modes in Navitia (or as fixed as possible).
On the other hand, the commercial_mode is not fixed, and can take any value.

We are working on a new data pipeline that will allow us to detect more easily those inconsistencies in physical_modes. Hopefully, you shouldn't have those errors anymore starting mid-2019. In the mean time, please notify us (using the GoogleGroup if possible).

I'll take a look at this NA value and see if we can fix it quickly.
Best regards

**Comment by prhod** [comment]
We've just fixed the issue and checked with TransportR.
Best

**Comment by schildbach** [comment]
Thanks a lot for your help.

**Comment by schildbach** [comment]
@prhod Region Finland still has `NA` PhysicalModes. Can you fix it there, too?

**Comment by prhod** [comment]
@schildbach thanks for the notification, I've warned our Data team. It should be fixed in a few days (sorry for the delay).

**Comment by ialokim** [comment]
@prhod [We've spot another one](https://gitlab.com/opentransitmap/public-transport-enabler/merge_requests/3#note_135423445) in the Region Portugal. Would be great if you could look after it, too.

**Comment by prhod** [comment]
@ialokim Portugal has been fixed. We are migrating the coverages (very ?) slowly to our new system. 9 for the moment. We will continue slowly as each coverage has particularities.

**Comment by ialokim** [comment]
@prhod Yeah, that's cool, I've already noticed Portugal has been fixed. Great to hear you are already into the process of migrating!

Btw, were there any changes applied on Navitia's side to how the geojson for trips is provided? Or were there any more changes on the Nicaragua provider? I've noticed Transportr to not show the paths following the roads anymore although Navitia's still providing the information. I think this is a client-side issue but if you have a clue, please refer to grote/Transportr/issues/585.
