### ISSUE TITLE
Negentwee departure dates are off by ~50 years

### ISSUE THREAD

**Issue by schildbach** [schildbach/public-transport-enabler#227]
That's because 9292.nl departure boards only shows the time (not the date) and we parse it as 1970-01-01. The problem is even worse on departure boards that wrap over the date ... the API doesn't make it clear that the early morning times are in fact on the next day.

@full-duplex Do you know if that problem is already discussed at 9292? IMHO ideally they would *always* use ISO 8601 (incl. date and TW) and be done with it.

**Comment by schildbach** [comment]
Workaround: start with the current date and increment by 1 if wraparound is detected. Of course this logic fails for days without service (e.g. on holidays), but it's better than nothing.

**Comment by full-duplex** [comment]
> Workaround: start with the current date and increment by 1 day if wraparound is detected.

The departures api doesn't support specifying a date (only supports "now"), so I suggest relying on the "Date" header from the server as starting point and count from there. Is there a way to access this value from a request result?

> Of course this logic fails for days without service (e.g. on holidays), but it's better than nothing.

9292 displays the time string as is, so this would confuse their users too. I'm assuming it only returns the next X hours of departures (or an empty list on days without service).

**Comment by full-duplex** [comment]
That works unless the local time is out of sync. I implemented the idea with other time related fixes here: https://github.com/schildbach/public-transport-enabler/pull/233.

**Comment by schildbach** [comment]
Fixed, seems as good as it gets (without improvements in the API).
