### ISSUE TITLE
Issue when searching connections in Transportr App

### ISSUE THREAD

**Issue by buteo2** [schildbach/public-transport-enabler#232]
I lately discovered a problem using Transportr App. The app says I should report it here so.. There is a screenshot attached. It happens every time I try to find a connection, meaning I cannot use the app at all right now. 

Kind regards

![tb](https://user-images.githubusercontent.com/43297218/46562067-c2c6fc80-c8fa-11e8-9ffa-f5c8e5bb3fa1.jpg)

**Comment by grote** [comment]
Thanks for the report. It would help to show which transportation network you are using.

**Comment by buteo2** [comment]
Hi, I'm using VRR (Germany). I have to add, it doen't happen using Deutsche Bahn for example. But that's not the best option for a lot of my connections unfortunately.

**Comment by schildbach** [comment]
I guess you were using a quite old Android device. Is it still an issue?

**Comment by buteo2** [comment]
Hi, yes it was an old Android device and meanwhile I changed to a new one. However I checked it on the old one and it seems to be no more an issue.
