### ISSUE TITLE
Navitia: No enum constant PhysicalMode.RAILSHUTTLE

### ISSUE THREAD

**Issue by schildbach** [schildbach/public-transport-enabler#236]
Exceptions of this kind are pouring in.

Example trip query: `from=stop_area:OIF:SA:59590 to=stop_area:OIF:SA:59675`

```
java.lang.IllegalArgumentException: No enum constant de.schildbach.pte.AbstractNavitiaProvider.PhysicalMode.RAILSHUTTLE
at java.lang.Enum.valueOf(Enum.java:257)
at de.schildbach.pte.AbstractNavitiaProvider$PhysicalMode.valueOf(AbstractNavitiaProvider.java:94)
at de.schildbach.pte.AbstractNavitiaProvider.parseLineProductFromMode(AbstractNavitiaProvider.java:620)
at de.schildbach.pte.AbstractNavitiaProvider.parseLineFromSection(AbstractNavitiaProvider.java:434)
at de.schildbach.pte.AbstractNavitiaProvider.parseLeg(AbstractNavitiaProvider.java:500)
at de.schildbach.pte.AbstractNavitiaProvider.parseQueryTripsResult(AbstractNavitiaProvider.java:583)
at de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:996)
```

**Comment by grote** [comment]
Looks like each Navitia region has its own physical modes that need to be found and mapped properly. Is this ParisProvider?

**Comment by schildbach** [comment]
Yes, it's ParisProvider.

I'm not sure about the region-specific modes though. So far, I haven't seen any brand names – which I'm sure would pop up if modes were region specific.

**Comment by grote** [comment]
I've seen ORLYVAL already which is a special airport train to Orly only existing in this API region (and not in FranceNorthWest or BritishColumbia).

**Comment by grote** [comment]
Maybe @prhod can clarify why there's things like ([`VAL`](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractNavitiaProvider.java#L95) for Orlyval) being returned as a physical mode while it is not even listed in the official documentation above.

**Comment by prhod** [comment]
Hello @grote @schildbach. You're right about a problem in the physical_modes: the `fr-idf` coverage (for Paris and around) contains this irregular `VAL` value. To correct it, we've added the `RailShuttle` physical_mode value some weeks ago, and we will change the `VAL` to `RailShuttle` ASAP. 
It way take a few weeks to be done.

**Comment by grote** [comment]
Thanks for the info! So I guess we just need to add the RailShuttle for now.

**Comment by schildbach** [comment]
Added via 3ffabe1d9bb412c69fd74eeadcdaf2f282c147a5.

At some point we should remove `PhysicalMode.VAL`.

**Comment by grote** [comment]
There's news" https://groups.google.com/d/msg/navitia/RM0KaWx_auY/YAOt3HnfCAAJ

>    * Physical mode "VAL" renamed "RailShuttle"
>    * Add of physical mode "SuspendedCableCar"
