### ISSUE TITLE
Data provider Denmark error

### ISSUE THREAD

**Issue by hoejmann** [schildbach/public-transport-enabler#242]
Getting the following error trying to do lookups:

java.net.UnknownServiceException: CLEARTEXT communication to mobilapps.rejseplanen.dk not permitted by network security policy
okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)

Let me know if any more information would be helpful!

**Comment by schildbach** [comment]
What OS and version are you running this on?

**Comment by hoejmann** [comment]
This is on Android 9, using Transportr 2.0.3 from F droid. Released 3 days ago. It is a bit unclear to me which version of public transport enabler this is using.

**Comment by hoejmann** [comment]
Possibly this

Implementation('com.gitlab.opentransitmap:public-transport-enabler:4354c4a8

**Comment by schildbach** [comment]
On recent Android versions, you need to provide a Network Security Configuration.

See https://developer.android.com/training/articles/security-config

**Comment by grote** [comment]
@hoejmann looking forward to your pull request for Transportr :)

**Comment by hoejmann** [comment]
Well I will certainly have a look and see if I can make any sense of if, but I am not much if a developer unfortunately.
