### ISSUE TITLE
Prague GTFS data

### ISSUE THREAD

**Issue by 12people** [schildbach/public-transport-enabler#245]
The city of Prague provides GTFS data as open data under the CC-BY license: http://opendata.praha.eu/dataset/dpp-jizdni-rady .

(More data about the system, including stop locations and GeoData, is available here: https://pid.cz/o-systemu/opendata/ .)

It'd be great if this data could be added.

**Comment by schildbach** [comment]
We can't simply add data. Rather, we need an API zu request this data from. Please check with navitia.io if they have this data already and if not ask them to add it.

**Comment by Nicky726** [comment]
Does this help?
https://navitia.opendatasoft.com/explore/dataset/czech-republic/information/

**Comment by 12people** [comment]
@schildbach Since Navitia has this information, can I count on it being included in Public Transport Enabler now?

**Comment by filip-hejsek** [comment]
Here is a PR: #276
