### ISSUE TITLE
VGS provider: updated interface

### ISSUE THREAD

**Issue by ialokim** [schildbach/public-transport-enabler#246]
Last Friday, the saarfahrplan app and website were updated for the first time since many years and now appears to use a new Hafas endpoint, so that pte can not query the information for now.

We should investigate if the `AbstractHafasMobileProvider` could now be used for the VGS provider.

**Comment by derhuerst** [comment]
> Last Friday, the saarfahrplan app and website were updated for the first time since many years [...].

I assume you're talking about the Android app?

**Comment by schildbach** [comment]
@derhuerst The website is entirely new, too. Turns out it's now the most modern ÖPNV page in Germany…

**Comment by derhuerst** [comment]
And still it doesn't redirect to HTTPS. 💩

**Comment by derhuerst** [comment]
> The website is entirely new, too. Turns out it's now the most modern ÖPNV page in Germany…

[It](https://www.saarfahrplan.de/) looks like a slightly updated version of the [CapMetro HAFAS mao UI](https://capmetro.hafas.cloud/index.html).

**Comment by derhuerst** [comment]
I have a [recording of it from 4 months ago](https://gist.github.com/derhuerst/d68678ba7f14fef0637bb3a530e51e0c) and a [recording of their iOS app from 2 months ago](https://gist.github.com/derhuerst/44d9b158ce6c7aef784631fb7ff87a66).

**Comment by schildbach** [comment]
Fixed via ef9c452166cf3cb65db81228dc0842390fc5f3ae.

Notes:

- The endpoint supports API version 1.23, but for now I only use 1.21. It doesn't support even lower versions than that.
- Sadly, the `stbFltrEquiv` problem is still unsolved. For now, as a workaround I'm ignoring the equivs parameter entirely from API level 1.19 on in 0da46fe14d090d7ef0811d0af127733d356fd9a8.

**Comment by schildbach** [comment]
> And still it doesn't redirect to HTTPS. hankey

At least it _supports_ HTTPS :smile:

**Comment by derhuerst** [comment]
We should make a list of features that have been added/removed for each HAFAS API version.
