### ISSUE TITLE
Navitia: queryDepartures results in INVALID_STATION

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#25]
@aelkhour When querying for departures with the Paris provider, I get an INVALID_STATION result. An example is Gare du Nord where I use the location.id "stop_area:RTP:SA:1958" for the query.

I see the same problem with other Navitia regions.

**Comment by aelkhour** [comment]
@grote Navitia has two separate types of stations: stop points, which correspond to a specific bus stop for a specific direction for a specific line, and stop areas, which can correspond to bus stops for all directions for all lines in a hub.

As a navitia departure query is different depending of station type, AsbstractNavitiaProvider relies for now on the equivs flag to distinguish the two cases. So your problem could be solved if you set the equivs flag to true.

Let me know if this solves the issue.

**Comment by grote** [comment]
@aelkhour I'm using equivs=true, but still the same problem. When I find some time, I'll try to provide a test case for you.

**Comment by grote** [comment]
Here's a test case:
```java
	@Test
	public void queryDeparturesStopArea() throws Exception
	{
		final int maxDepartures = 5;
		final QueryDeparturesResult result = queryDepartures("stop_area:RTP:SA:1958", maxDepartures, true);
		assertEquals(QueryDeparturesResult.Status.OK, result.status);
		assertTrue(result.stationDepartures.size() > 1);
		print(result);
	}
```
Looks like it has indeed to do with "stop_area". However, I'd like this to work as I get these stop_areas from the auto-completion and as stop locations in trips.

**Comment by aelkhour** [comment]
@grote Fixed, please test.

**Comment by grote** [comment]
works great, thanks for fixing!
