### ISSUE TITLE
BahnProvider: PARSE error on the response of some TripSearch requests

### ISSUE THREAD

**Issue by schildbach** [schildbach/public-transport-enabler#251]
Running this code on BahnProvider yields a PARSE error on the reponse (!). According to the error description, the problematic JSON node is `root.svcResL.svcResL.res.outConL.outConL.secL.secL.type` but we never get to see the actual JSON response. Not all TripSearch requests are affected by this. It seems to affect mainly trips from or to "area" locations (not actual stops but entire cities, usually written in allcaps). Seems like this can only be fixed by Hacon.

Code:
```
final Location from = new Location(LocationType.STATION, "8096021"); // FRANKFURT(MAIN)
final Location to = new Location(LocationType.STATION, "8096022"); // KÖLN
final QueryTripsResult result = queryTrips(from, null, to, new Date(), true, null);
```

Request (auth and client redacted):
```
{"auth":xxx,"client":xxx,"ver":"1.17","lang":"eng","svcReqL":[{"meth":"ServerInfo","req":{"getServerDateTime":true,"getTimeTablePeriod":false}},{"meth":"TripSearch","cfg":{"polyEnc":"GPA"},"req":{"depLocL":[{"type":"S","extId":"8096021"}],"arrLocL":[{"type":"S","extId":"8096022"}],"outDate":"20190103","outTime":"165400","outFrwd":true,"gisFltrL":[{"mode":"FB","profile":{"type":"F","linDistRouting":false,"maxdist":2000},"type":"M","meta":"foot_speed_normal"}],"getPolyline":false,"getPasslist":true,"getIST":false,"getEco":false,"extChgTime":-1}}],"formatted":false}
```

Response:
```
{"ver":"1.17","lang":"eng","id":"sfgwfpdwgagwwwww","err":"PARSE","errTxt":"Parser error: root.svcResL.svcResL.res.outConL.outConL.secL.secL.type","cInfo":{"code":"OK","url":"","msg":""},"svcResL":[]}
```

**Comment by schildbach** [comment]
Here is a quite minimal request that also shows the issue:

```
{
   "auth":xxx,
   "client":xxx,
   "ver":"1.17",
   "lang":"deu",
   "svcReqL":[
      {
         "meth":"TripSearch",
         "req":{
            "depLocL":[
               {
                  "type":"S",
                  "extId":"8096021"
               }
            ],
            "arrLocL":[
               {
                  "type":"S",
                  "extId":"8096022"
               }
            ]
         }
      }
   ]
}
```

**Comment by schildbach** [comment]
More fun: by increasing the API version to 1.21 and beyond, HCI produces an indeed unparseable JSON.

Request:
```
{"auth":{"type":"AID","aid":"n91dB8Z77MLdoR0K"},"client":{"id":"DB","v":"16040000","type":"AND","name":"DB Navigator"},"ver":"1.21","lang":"deu","svcReqL":[{"meth":"TripSearch","req":{"depLocL":[{"type":"S","extId":"8096021"}],"arrLocL":[{"type":"S","extId":"8096022"}]}}]}
```

Response:
```
{"ver":"","lang":"deu","id":"","err":"VERSION","errTxt":"Invalid version: 1.21","svcResL":[],"svcResL":[]}
```

Exception:
```
org.json.JSONException: Duplicate key "svcResL"
	at org.json.JSONObject.putOnce(JSONObject.java:1076)
```

**Comment by derhuerst** [comment]
> According to the error description, the problematic JSON node is `root.svcResL.svcResL.res.outConL.outConL.secL.secL.type` but we never get to see the actual JSON response.

Isn't that a bug in itself? Shouldn't it be `root.svcResL.res.outConL.secL.type`?

> Here is a quite minimal request that also shows the issue: [...]

Can't reproduce right now (`2019-01-04T05:02:34Z`).

> More fun: by increasing the API version to `1.21` and beyond, HCI produces an indeed unparseable JSON.
>
> [...]
> ```
> {"ver":"","lang":"deu","id":"","err":"VERSION","errTxt":"Invalid version: 1.21","svcResL":[],"svcResL":[]}
> ```

True but only when responding with an error, or does it also happen with "regular" responses?

**Comment by schildbach** [comment]
Ah, `"ext":"DB.R15.12.a"` does the trick. I wasn't aware this is needed.

**Comment by schildbach** [comment]
Fixed.

**Comment by derhuerst** [comment]
So because [`hafas-client` does send `ext`](https://github.com/public-transport/hafas-client/blob/ecc26ef313b75f9bedcf4ee1b2b95aebb3478379/p/db/index.js#L15), 
https://github.com/public-transport/hafas-client/issues/101 can be closed?
