### ISSUE TITLE
Java exception in Belgium with sncb

### ISSUE THREAD

**Issue by lgiard** [schildbach/public-transport-enabler#256]
I see this java exception every time i try to use the transportr app in Belgium, it is apparently related to public-transport-enabler directly (as the error message mentions it). Looking at the error, it looks related to belgianrail api.

![image](https://user-images.githubusercontent.com/25881921/51236623-e9bdb180-1972-11e9-92cd-6b2814be4834.png)

**Comment by schildbach** [comment]
Can you please paste the exception as text?

**Comment by lgiard** [comment]
Here it is, i don't know if the indentation/line are respected or not. 

```
de.schildbach.pte.exception.UnexpectedRedirectException:
http://www.belgianrail.be/jp/sncb-nmbs-routeplanner/quary.exe/nn?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8814001&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8812005&REQ0HafasSearchForw=1&REQ0JourneyDate=16.01.19&REQ0JourneyTime=10%3A49&REQ0JourneyProduct_prod_list_1=1010011011100000&h2g-direct=11&clientType=ANDROID -> https://wwww.belgiantrain.be/nl?start=Suchen&REQ0JourneyStopsS0ID=A%3D1%40L%3D8814001&REQ0JourneyStopsZ0ID=A%3D1%40L%3D8812005&REQ0HafasSearchForw=1&REQ0JourneyDate=16.01.19&REQ0JourneyTime=10%3A49&REQ0JourneyProduct_prod_list_1=1010011011100000&h2g-direct=11&clientType=ANDROID
de.schildbach.pte.util.HttpClient.
getInputStream(HttpClient.java:245)
de.schildbach.pte.util.HttpClient.
getInputStream(HttpClient.java:163)
de.schildbach.pte.util.HttpClient.
getInputStream(HttpClient.java:159)
```

**Comment by schildbach** [comment]
It looks like you typed it by hand? There are spelling errors in the URL.

Please get back to the authors of Transportr to tell you how to retrieve the exact stacktrace as text.

**Comment by schildbach** [comment]
Ok, now it is correct, but it's an old version of PTE. SNCB has moved to HCI a couple of months ago. If you use the current version it will work.
