### ISSUE TITLE
AbstractNavitiaProvider: Use UTC times

### ISSUE THREAD

**Issue by ialokim** [schildbach/public-transport-enabler#260]
As stated in grote/Transportr#577 by @schildbach:
> the API is UTC time for both request and response

This is currently not implemented for `AbstractNavitiaProvider` and therefore neither for all of the several providers using Navitia's API. The necessary changes would be in [line 320](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractNavitiaProvider.java#L320) and 324, respectively.

**Comment by ialokim** [comment]
@schildbach checking the sources e.g. for `AbstractHafasMobileClientProvider`, it seems `queryTrips` expects the `time` given in `CEST` (see [line 547](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractHafasClientInterfaceProvider.java#L547)) as `timeZone` is set [inside `AbstractNetworkProvider`](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractNetworkProvider.java#L54) and not as `UTC`.

So I'm not sure I understood you correctly: Did you refer to the official endpoint APIs (Hafas, Navitia, Efa) which expect UTC time or did you really refer to the `queryTrips` method inside PTE?

**Comment by schildbach** [comment]
If I see this correctly, then what you're quoting is a conversion from UTC (the Date object) to the local time of the provider (by using the various getters in jsonDate() / jsonTime().

The network APIs usually expect local time (whatever that means is unclear – some networks span more than one timezone). The PTE Java API expects UTC.

**Comment by ialokim** [comment]
Okay I think I got it now: the `Date` object itself is independent of timezones, so it is indeed UTC. Thanks for the explanation!

So the issue still persists for `AbstractNavitiaProvider`.

**Comment by schildbach** [comment]
Fixed via #261.
