### ISSUE TITLE
Issues with TLEM searches not working. 

### ISSUE THREAD

**Issue by ArmitageShanks** [schildbach/public-transport-enabler#262]
I submitted this issue to the Transport github before, but was told that the issue is with public-transport-enabler. 

https://github.com/grote/Transportr/issues/601

> 
> Describe the bug
> When I use the search function to find a "from" or "to" location it works extremely seldom (unless the station is stored in history,and what's stored in history is a mystery on a new device since so few stations can be found).
> This is not an issue I had before.
> 
> I use TLEM and when you put in a MAJOR station in London like Paddington or Victoria nothing shows up (unless the station is in your history)
> 
> To Reproduce
> Steps to reproduce the behavior:
> 
>     Go to Transportr
>     Click on search box
>     Type in "Paddington"
>     See nothing
> 
> Expected behavior
> To see a bunch of options showing Paddington in their names.
> 
> Versions (please complete the following information):
>     **Transportr Version 2.0.5
>     ** Nexus 6P and Poco phone F1
>     **Android Version 8.1 and 9.
> 
> 

And I got this response:

> Transportr hasn't changed. It uses the API provided by TLEM. So this is what might have changed. Looks like https://github.com/schildbach/public-transport-enabler/ wasn't adapted either. This is what would need to be adapted for a changed API, not Transportr itself.

**Comment by schildbach** [comment]
Must be an issue in Transportr. I have no troubles getting correct suggestions via `TlemProviderLiveTest.suggestLocations()`, and in Öffi it works too (incl. querying for trips between Paddington and Victoria stations).

**Comment by ArmitageShanks** [comment]
I just installed Öffi, and you are indeed correct. Everything is working fine there. Thanks for the reply and thanks for suggestion Öffi, awesome looking app.

**Comment by schildbach** [comment]
Thanks, I'm glad you like it.
