### ISSUE TITLE
Quebec: Intermodal change (bus-metro) not possible at Vendome (Montreal)

### ISSUE THREAD

**Issue by laborhase** [schildbach/public-transport-enabler#263]
Hello there,
I noticed that Transportr never offers any connections that would need a change from bus to metro (or vice versa) at Vendome (Montreal) but instead makes complicated bus-bus and bus-commuter train combinations or takes a route via another metro entry that can take up to 20 min longer. I guess that is one of the reasons Quebec is listed as "alpha". What can be done about that?

**Comment by grote** [comment]
@laborhase The data comes from Navitia. I suggest you check their Playground for the same query and see if they offer the changes.

**Comment by laborhase** [comment]
Alright, I'll look into that.

**Comment by laborhase** [comment]
I just cross-checked the queries in Transportr and on Navitia Playground and they give exactly the same results. Also, I learned that Navitia does not compute the transfers but is provided with it ([https://github.com/CanalTP/navitia/issues/2478#issuecomment-410232208](url)) and I'll need to dig into the Navitia Google group for this issue.

**Comment by schildbach** [comment]
Thanks for the feedback!
