### ISSUE TITLE
Italy: search doesn't work

### ISSUE THREAD

**Issue by adolfintel** [schildbach/public-transport-enabler#264]
![Screenshot_20190503-172907_Transportr](https://user-images.githubusercontent.com/16307689/57180313-bf432600-6e87-11e9-91ef-73a3df02f0d2.png)

**Comment by schildbach** [comment]
@prhod This is another one of these invalid physical mode values "NA", this time for the Italy region.

**Comment by prhod** [comment]
thanks for the notification, the problem has been transferred to our Data team.

**Comment by AndreyPankratov** [comment]
@schildbach we have updated modes for Italy, should no longer show "NA".

**Comment by schildbach** [comment]
Thanks!

@adolfintel I'm closing this.
