### ISSUE TITLE
error on query

### ISSUE THREAD

**Issue by amo13** [schildbach/public-transport-enabler#268]
The pictured query works fine with the Deutsche Bahn network but gives this error when using the NVV network (Germany)
![Screenshot_20190625-213838_Transportr](https://user-images.githubusercontent.com/6617661/60128289-9148d680-9792-11e9-88ae-d1fe6fe065c5.png)

I would also like to point out that the link to this issue tracker (seen as "public-transport-enabler" on the screenshot) is broken and yields to a 404 github page.

**Comment by sedrubal** [comment]
The same error happens for navigations with "Bahnhof Georgensgmünd" in VGN network.

**Comment by schildbach** [comment]
This issue is _not_ related to public-transport-enabler. Please report it upstream.
