### ISSUE TITLE
AbstractNavitiaProvider: use full url for TripQuery

### ISSUE THREAD

**Issue by ialokim** [schildbach/public-transport-enabler#275]
As pointed out (some time ago) in [this issue](https://github.com/grote/Transportr/issues/583#issuecomment-466106840), `AbstractNavitiaProvider` does not add `coverage` information into the url when searching for a trip (on endpoint `journeys`), see [here](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractNavitiaProvider.java#L902).

This does not cause any problems when there is no error as Navitia can handle queries without the `coverage` part. But in the case of an invalid station, it seems to make a difference: Navitia's returning a `BlockedException` instead of the `invalid_station` flag.

I guess this could be solved by simply adding the `coverage` part into the url as done in all the other methods (e.g. `suggestLocations`). They use the method `url()` which returns the base path including the `coverage`.

If you want me to do so, I could make the necessary change and open an PR.

**Comment by grote** [comment]
I think we should add the coverage info to the URL.

**Comment by ialokim** [comment]
(pinging @aelkhour and @schildbach for comments as they seem to be the main authors of this NetworkProvider)

**Comment by ialokim** [comment]
Some thoughts on this @schildbach ?

**Comment by schildbach** [comment]
I'm not an expert on the Navitia API. From your description, it sounds like a reasonable thing to do. Feel free to submit a PR.

**Comment by schildbach** [comment]
Fixed via #295.
