### ISSUE TITLE
Data for Spain (Bilbao) is incomplete

### ISSUE THREAD

**Issue by Nutomic** [schildbach/public-transport-enabler#279]
The dataset for Spain seems to be [this one](https://navitia.opendatasoft.com/explore/dataset/es/information/). According to the description, it includes the metro and tram in Bilbao. However, I dont get any metro/tram connections shown, neither in Öffi nor in Transportr (both latest version from F-Droid).

These screenhots show a connection search directly from one metro station to another, but it only suggests bus lines (or even walking).
![Screenshot_20190823-142337_�ffi](https://user-images.githubusercontent.com/1044450/63592493-3c161f00-c5a1-11e9-9240-11a83d51fa4e.png)
![Screenshot_20190823-142348_Transportr](https://user-images.githubusercontent.com/1044450/63592497-3d474c00-c5a1-11e9-8014-ec79d2bb9b67.png)

I would be happy to help with this, if you can tell me how to.

**Comment by pespin** [comment]
Same issue in Barcelona, which uses the same dataset (Naivita "es"). The "metro" (underground) never shows up when asking for a route, only bus and Ferrocarrils de la Generalitat de Catalunya (FGCC, similar kind of transpot  as S-Bahn in Berlin).

**Comment by pespin** [comment]
The issue in Bilbao and Barcelona seems to be different though.
I downloaded the GTFS file from Navitia and I see the Metro of Bilbao in agency.txt, but I see no entry for the Barcelona one:
`E32:1,Metro Bilbao,http://www.metrobilbao.eus,Europe/Madrid,ES,+34 94 425 40 25,`

There seems to be only one entry in routes.txt:
`routes.txt:680:E32:MB,E32:1,,Línea De Metro Bilbao,,1,,FF6505,,`

However, content in stop_extensions.txt, stops.txt, transfers.txt, trips.txt and stop_times.txt seems to be using the ID with a postfix ".0" added, not sure if that's expected: `E32:1.0`

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
