### ISSUE TITLE
Lookup error when using VVO(Dresden) backend in Transportr

### ISSUE THREAD

**Issue by nek0** [schildbach/public-transport-enabler#281]
When looking up a connection the enclosed error message pops up.
![Screenshot_20190927-181648_Transportr](https://user-images.githubusercontent.com/1859691/65785155-093ce900-e154-11e9-974b-4bc8ef1c9a9c.png)

**Comment by schildbach** [comment]
This report is missing the stack trace relevant to public-transport-enabler.
