### ISSUE TITLE
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by sedrubal** [schildbach/public-transport-enabler#286]
I'm using Transportr and VGN-Network and for some stops I get this exception:

<details>
<summary>Error description</summary>
<pre>
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:832)
android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
</pre>
</details>

![Screenshot_20191108-170222_Transportr](https://user-images.githubusercontent.com/5571650/68490640-aad25280-0249-11ea-84ff-6aef48018356.png)

I think more and more stations have this problem...
Deleting the app data fixes the problem.

**Comment by grote** [comment]
Sorry, contrary to the message below this is a Transportr issue and not related to public-transport-enabler.
