### ISSUE TITLE
Missing results in Sweden

### ISSUE THREAD

**Issue by ahstro** [schildbach/public-transport-enabler#288]
I'm using [Transportr](https://github.com/grote/Transportr), but I'm not getting any results for any station in Sweden. After typing in anything in the search bar, a spinner is shown for a second but nothing shows up. Works with different locations, such as Belgium and Deutsche Bahn.

**Comment by regagain** [comment]
It could be the same issue as #266, which is fixed but Transportr hasn't been updated since then.

**Comment by ahstro** [comment]
@regagain It doesn't end up with a screen looking the same as in that issue, which is why I assumed it was a different error. We'll see when https://github.com/grote/Transportr/issues/649 is fixed (thanks for creating that 😊)

**Comment by regagain** [comment]
This is fixed in Transportr 2.0.7.

**Comment by ahstro** [comment]
Whoop! Transportr 2.0.8 is now out on F-Droid and this was, indeed, fixed 🥰
