### ISSUE TITLE
FRANCENORTHEAST: java.lang.NullPointerException

### ISSUE THREAD

**Issue by BoboTiG** [schildbach/public-transport-enabler#289]
### Query
- NetworkId: `FRANCENORTHEAST`
- From: `Location{ADDRESS, 49.1154880/6.1740810, place=Metz, name=Rue du Coëtlosquet}`
- Via: `null`
- To: `Location{ADDRESS, 49.0827550/6.1837920, place=Metz, name=Rue du Faubourg 41}`
- Date: `Wed Dec 25 22:55:33 GMT+01:00 2019`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.NullPointerException
com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
de.schildbach.pte.dto.Style.parseColor(Style.java:108)
de.schildbach.pte.FranceNorthEastProvider.getLineStyle(FranceNorthEastProvider.java:68)
```

**Comment by schildbach** [comment]
This has been fixed via 7f607160ca919bd68628d867f0a80972c7a471ae.
