### ISSUE TITLE
Paris (France) : missing part of the RER B in the south of Paris

### ISSUE THREAD

**Issue by nerg-max** [schildbach/public-transport-enabler#297]
Hello,
After search on the transportr app, I realize that the South part of the RER B is missing.
I hope my report useful.
(Sorry for bad english)

**Comment by schildbach** [comment]
Can you check on navitia.io, if the issue occurs there too? If yes, then would you get in contact with them? We have no leverage on the data itself.

**Comment by nerg-max** [comment]
Thank for your answer, but since few days, the RER B has come back.
Sorry for opening this issue.  (and for bad English)
