### ISSUE TITLE
PLNAVITIA: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by Baarten** [schildbach/public-transport-enabler#299]
### Query
- NetworkId: `PLNAVITIA`
- From: `Location{ADDRESS, 49.3281820/19.8687570, place=Dzianisz, name=Dzianisz}`
- Via: `null`
- To: `Location{POI, 49.2941890/19.9466450, place=Zakopane, name=Jardin}`
- Date: `Thu Jan 09 18:59:18 GMT+01:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1060)
de.schildbach.pte.AbstractNetworkProvider.queryTrips(AbstractNetworkProvider.java:92)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:109)
```

### Additional information
UI language: Dutch
Public transit: Municipal Transports of Poland
Device: Xiaomi Mi 8 (dipper)
OS: LineageOS 16.0-20191231-microG-dipper
Transportr version: 2.0.8

**Comment by schildbach** [comment]
This is an error returned by the Navitia.io API. We need to check with their API why this error occurs. Yes, we don't have location IDs for POIs or Addresses. Could we, perhaps?

**Comment by ialokim** [comment]
This is likely to be the same issue as https://github.com/grote/Transportr/issues/424
and also duplicates of #310, #322, #318, #317 and #307.

**Comment by mimi89999** [comment]
Hello
What have you entered in from and to fields in Transportr?

If I enter the coordinates in Navitia playground, I get `Public transport is not reachable from origin nor destination`. That's expected since there is no data in Navitia for public transport in the city of Zakopane.

**Comment by Baarten** [comment]
> Hello What have you entered in from and to fields in Transportr?

Hi, I think I entered from “Dzianisz” to “Zakopane”, but I don't know why it says “Jardin” in my report. If I try to search that with “zakopane” in Transportr, I get a list of gardens in Zakopane. Verifying with the coordinates, the coordinates do point to a garden, but I don't remember entering that.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
