### ISSUE TITLE
VMS: NO_TRIPS

### ISSUE THREAD

**Issue by D1rkW0** [schildbach/public-transport-enabler#305]
### Query
- NetworkId: `VMS`
- From: 
- Via: `null`
- To: `Location{STATION, 36040494, 50.4802170/12.9742240, place=Neudorf (Erzgeb), name=Gh Kaiserhof}`
- Date: `Fri Feb 28 15:14:09 GMT+01:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
Keine Verbindungen gefunden :(
```

### Additional information
Hello,
actually all connections to a Stop in Neudorf (Erzgeb) currently return an error. "Handyticket Deutschland" for example returns correct connections when searching from:
Sehma, untere Brücke
to:
Neudorf (Erzgeb), Gh Kaiserhof

Transportr also returns correct connections when using the street address, like:
"Sehmatal, Karlsbader Straße (Neudorf) 171"

Around 1..2 months ago it worked correctly for Neudorf (correcter: Sehmatal-Neudorf).
Thank you for checking and hopefully fixing this !

A happy transportr user

**Comment by DirkWolff** [comment]
I just discovered the search above was for a passed date/time. Searching again with current timestamp returns results again. 
And subsequently even results for dates passed (even few days ago). So I don't know why it didn't work the last days..
Thanx

**Comment by schildbach** [comment]
So can this be closed?

**Comment by D1rkW0** [comment]
If it doesn't give you any more clues ,yes. I will monitor if app behaves stable. 
Thank you
