### ISSUE TITLE
Discrepancy among different sources

### ISSUE THREAD

**Issue by killermoehre** [schildbach/public-transport-enabler#306]
Hi,

following routing:
Germany, Dresden, Mohnstraße 30
to
Germany, Dresden, Könneritzstraße 7

If I look this route up online at https://www.vvo-mobil.de it tells me to walk to `Altpieschen` and take the tram there, as expected. If I use Öffi or Transportr for this route using the provider `DB` (Deutsche Bahn), I get the same result. But if I use the provider `VVO` (Verkehrsverbund Oberelbe) than I should walk to `Oschatzer Straße` – a whole stop away – instead of using the close station `Altpieschen`.

**Comment by schildbach** [comment]
That's actually expected. The different systems have different data, use different algorithms, parameters, etc. If you think some query result is incorrect or suboptimal, I suggest to get in contact with the respective public transit authority.

**Comment by killermoehre** [comment]
The point here is that only this project is showing the undesired route and I can't seem to get it fixed.
I don't understand why there is a difference between VVO itself and the provider VVO in the `public-transport-enabler`.

**Comment by schildbach** [comment]
Ok, but that's an entirely different issue. For the VVO it might be cause by slightly different EFA parameters. Something like "shortest time" on one hand and "least changes" on the other. I suggest using the Firefox Developer Tools to thoroughly compare all the query parameters to `XSLT_TRIP_REQUEST2` to learn what's needed to get the exact same results (for PTE, the queries incl. parameters are logged).

**Comment by killermoehre** [comment]
Ok, now it works again in both transportr and Öffi. I don't know why. Maybe something at the API was changed. Sorry for the noise.
