### ISSUE TITLE
FRANCESOUTHEAST: java.lang.NullPointerException

### ISSUE THREAD

**Issue by hellpe** [schildbach/public-transport-enabler#309]
### Query
- NetworkId: `FRANCESOUTHEAST`
- From: `Location{STATION, stop_area:OM1:SA:Navitia:1407, 43.2862110/5.3853750, place=Lodi, name=Baille Castellane}`
- Via: `null`
- To: `Location{ADDRESS, 43.4797480/5.3724910, place=Aix-en-Provence, name=Rue Paul Langevin}`
- Date: `Fri May 15 17:49:47 GMT+02:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.NullPointerException
com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
de.schildbach.pte.dto.Style.parseColor(Style.java:108)
de.schildbach.pte.FranceSouthEastProvider.getLineStyle(FranceSouthEastProvider.java:57)
```

### Additional information

How to reproduce this error, with the Europe/France/South-East map:

1. Tap the direction icon
2. Put "Baille Castellane, Castellane" (https://www.openstreetmap.org/node/1327850425#map=19/43.28624/5.38537) in the start point
3.  Put "Rue Paul Langevin, Aix-en-Provence" (https://www.openstreetmap.org/way/23791927) in the end point
4. A `NullPointerException` appears.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
