### ISSUE TITLE
WIEN: INVALID_DATE

### ISSUE THREAD

**Issue by Elettrotecnica** [schildbach/public-transport-enabler#344]
### Query
- NetworkId: `WIEN`
- From: `Location{ADDRESS, streetID:3464:16:49000001, 48.2152450/16.3395290, place=Wien, name=Wien, Ottakringer Straße 16}`
- Via: `null`
- To: `Location{ADDRESS, streetID:2002:3:49000001, 48.2188500/16.3306600, place=Wien, name=Wien, Hormayrgasse 3}`
- Date: `Wed Dec 16 12:17:32 GMT+01:00 2020`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
Il provider dei dati non supporta attualmente la ricerca per data. Riprova con un'altra data.
```

### Additional information
The error in italian says "The data provider does not currently support searching by date. Try with a different date"

It used to work perfectly fine in the past.

I am running transportr app version 2.1.0

Thanks for any support on this and thanks for this great service. Please let me know if additional info is needed.

**Comment by schildbach** [comment]
It's likely a re-occuring problem with Wiener Linien. They forget to upload the new timetable data to their dedicated open data server (which public-transport-enabler is using).

**Comment by Elettrotecnica** [comment]
Thanks for the pointer. Is there anything one can do to make them aware of the problem?

**Comment by schildbach** [comment]
Tell them that their Open Data EFA Server is out of date, like every year around Dec 11th. It might sense to check again before you write to them, because maybe they fixed it already.

**Comment by sphh** [comment]
I just sent them an email. Most likely we have to wait for post-Christmas time ;-)

**Comment by Elettrotecnica** [comment]
Thanks a lot, I have sent an email as well and they confirmed the issue and told me they are already addressing it. 

My best regards

**Comment by sphh** [comment]
Thanks @Elettrotecnica! May I ask, when did you send it?

**Comment by Elettrotecnica** [comment]
Sure, I have sent it on the 18th of December and got an answer on the 21st, sorry for not positing it earlier

All the best

**Comment by sphh** [comment]
Thanks. I haven't received any reply yet (which I do not really expected, since I sent my email on Dec 24th).

**Comment by schildbach** [comment]
Interesting info: https://www.data.gv.at/katalog/dataset/9c203fec-dc0d-412c-a7a3-7fd77d0346f1

**Comment by sphh** [comment]
Thanks for checking. So we'll blame those creeping gremlins!

When I followed up my earlier email to WienerLinien from before Christmas, I got this reply on 21st January:

> Das Update der Fahrpläne auf Open Data ist zurzeit leider nicht möglich. Wir arbeiten bereits an der Problemlösung und bitten bis dahin um Geduld.

meaning
> The update of the routing data to Open Data is currently not possible. We work to solve this glitch and to ask for your patience until it is solved.

We'll see, if they have ironed out this glitch until their next adjustment of the timetable in June.

**Comment by sphh** [comment]
I just tried today and I got a connection in `Öffi` and `Transportr`, so it looks like it is working again.

Mind you, I have not received any email from them telling me that it is working again, but I think this issue can be closed.

**Comment by schildbach** [comment]
Indeed, it's working again. Thanks to everyone who helped with getting the word out to Wiener Linien!
