### ISSUE TITLE
Blocked connection to data provider WienerLinien

### ISSUE THREAD

**Issue by sphh** [schildbach/public-transport-enabler#355]
Bug #344 describes an error with regard to a wrong date. After contacting the relevant authorities, we were told to wait. When I tried today, I got a `Connection refused by www.wienerlinien.at` (`Öffi`). `Transportr` gave the following more elaborate error message:
```javascript
de.schildbach.pte.exception.BlockedException: https://www.wienerlinien.at/ogd_routing/XSLT_TRIP_REQUEST2?outputFormat=XML&language=de&stateless=1&coordOutputFormat=WGS84[DD.ddddd]&coordOutputFormatTail=7&sessionID=0&requestID=0&coordListOutputFormat=string&type_origin=address&name_origin=streetID%3A2399%3A5%3A49000001&type_destination=address&name_destination=streetID%3A2979%3A12A%3A49000001&itdDate=20210202&itdTime=1226&itdTripDateTimeDepArr=dep&calcNumberOfTrips=6&ptOptionsActive=1&itOptionsActive=1&routeType=LEASTTIME&changeSpeed=fast&includedMeans=checkbox&inclMOT_0=on&inclMOT_14=on&inclMOT_15=on&inclMOT_16=on&inclMOT_0=on&inclMOT_13=on&inclMOT_1=on&inclMOT_2=on&inclMOT_3=on&inclMOT_4=on&inclMOT_5=on&inclMOT_6=on&inclMOT_7=on&inclMOT_9=on&inclMOT_8=on&inclMOT_10=on&useProxFootSearch=1&trITMOTvalue100=10&locationServerActive=1&useRealtime=1&nextDepsPerLeg=1&inclMOT_11=on
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:284)
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:218)
de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2101)
```

Are they now blocking all external connections?

Does anybody has an idea, how to persuade the data provider to not block requests?

**Comment by schildbach** [comment]
Interesting info: https://www.data.gv.at/katalog/dataset/9c203fec-dc0d-412c-a7a3-7fd77d0346f1

**Comment by schildbach** [comment]
The URL is still up to date according to this document: https://www.data.gv.at/katalog/dataset/stadt-wien_wienerlinienroutingservice/resource/1b327661-a3c6-4929-8112-c8655f78ad1c

**Comment by sphh** [comment]
Thanks for checking. I was not even aware of this website!

Since the URL is still valid, I am happy to close this issue and track it in #344. What do you think, @schildbach?

**Comment by schildbach** [comment]
Yes, good idea.

**Comment by schildbach** [comment]
Duplicate of #344
