### ISSUE TITLE
Bus line "Garaiar" from Basque Country (Spain) disappeared

### ISSUE THREAD

**Issue by Porrumentzio** [schildbach/public-transport-enabler#358]
Since some versions, the bus line named Garaiar (G1, G2, G3...) are not longer available in Transport.
There must have been some kind of problem.

It's on Gipuzkoa province, Basque Country (Spain)

**Comment by Porrumentzio** [comment]
This has something to see with Nativia's data, with the Lurraldebus section from Spain:
https://navitia.opendatasoft.com/explore/dataset/es/information/?sort=type_file

**Comment by schildbach** [comment]
You should report this to Navitia. Public-transport-enabler can only pass on correct information if it gets correct information from the web services.
