### ISSUE TITLE
No data from Luxembourg transport provider

### ISSUE THREAD

**Issue by cliovincent** [schildbach/public-transport-enabler#359]
The Luxembourgish provider ("Verkéiersverbond") doesn't give any information in the app (version 2.1.0).

**Comment by derhuerst** [comment]
Have you tried multiple queries? Can you give an example where there are no results.

I didn't check with PTE, but with the [HAFAS webapp available on the same endpoint](https://cdt.hafas.de/#!P%7CTP!histId%7C1!histKey%7CH112483) as PTE uses.

With the webapp, querying connections from Luxembourg Gare cebtrale to Marsche Gare worked. There seems to be a bug where ut doesn't show the multimodel connections first, but if you switch to the public-transport-only connections and then back, it works.

**Comment by cliovincent** [comment]
Thanks for your reply. I have tried different queries over the last few weeks, but it never worked. An example would be "Bettembourg gare to Luxembourg gare".

**Comment by derhuerst** [comment]
Then it's probably due to how PTE talks to the endpoint, not due to the endpoint itself (e.g. missing data).

**Comment by derhuerst** [comment]
Do you get an error or just 0 results? I just noticed that the HAFAS endpoint doesn't support IPv6. 🙄

```shell
$ ping6 cdt.hafas.de
# ping6: UDP connect: No route to host
$ ping cdt.hafas.de
# PING ext02-ha.hacon.de (83.246.89.20): 56 data bytes
# 64 bytes from 83.246.89.20: icmp_seq=0 ttl=57 time=33.812 ms
# 64 bytes from 83.246.89.20: icmp_seq=1 ttl=57 time=82.736 ms
# ^C
# --- ext02-ha.hacon.de ping statistics ---
# 2 packets transmitted, 2 packets received, 0.0% packet loss
# round-trip min/avg/max/stddev = 33.812/58.274/82.736/24.462 ms
```

**Comment by cliovincent** [comment]
There is no error message, just no suggestions when you start typing, and no results.

**Comment by schildbach** [comment]
I *do* get suggestions if I start typing "Luxemb…". Can you run "adb logcat" in parallel and see if there are any network errors on your side?

**Comment by ialokim** [comment]
Hi @cliovincent, if you are using Transportr, the fix should be available with the next update (which has unfortunately been delayed due to lack of time). Also see https://github.com/grote/Transportr/issues/729.

This issue could be closed here as it is not present in PTE anymore.

**Comment by cliovincent** [comment]
That is great news, I'll install the update as soon as it is available. Thanks a lot!
