### ISSUE TITLE
No results for NS trips

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [schildbach/public-transport-enabler#363]
Everytime i want to plan  a trip i get this errordump:

https://user-images.githubusercontent.com/73130443/112456141-bea52880-8d5a-11eb-8bda-df3ff0d07fc0.mp4

**Comment by derhuerst** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc Is this error resolved? Or does it still happen with the latest app version?

This seems to be a duplicate of #428.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I closed this because it is a duplicate
