### ISSUE TITLE
[BVG not working] BVG: java.io.IOException: got response: 307 Temporary Redirect: https://bvg-apps.hafas.de/bin/mgate.exe

### ISSUE THREAD

**Issue by rafaces** [schildbach/public-transport-enabler#386]
### Context
BVG connection not working, getting java.io.IOException. See details below (I've removed my coordinates and some address information for privacy)

### Query
- NetworkId: `BVG`
- From: `Location{ADDRESS, 52.0000000/13.0000000, place=Berlin, name=STREET NAME HERE}`
- Via: `null`
- To: `Location{ADDRESS, A=2@O=10117 Berlin-Mitte, Oranienburger Str. 70@X=13393136@Y=52524906@U=103@L=770002363@B=1@p=1592347662@, 52.5249060/13.3931360, place=10117 Berlin-Mitte, name=Oranienburger Str. 70}`
- Date: `Thu Aug 12 18:35:38 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.io.IOException: got response: 307 Temporary Redirect: https://bvg-apps.hafas.de/bin/mgate.exe
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:293)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonLocMatch(AbstractHafasClientInterfaceProvider.java:468)
```

**Comment by schildbach** [comment]
This is already fixed via 20392732fa61cefae3bf2a1ab9da26d5b763227f.
