### ISSUE TITLE
HUNGARY: de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/hu/journeys?from=19.040359%3B47.497993&to=19.040359%3B47.497993&datetime=20210902T222253&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12

### ISSUE THREAD

**Issue by tudos4** [schildbach/public-transport-enabler#398]
![Screenshot_20210902-222727](https://user-images.githubusercontent.com/34228681/131911576-2eb7424c-a4bd-445d-bf70-79757da36774.png)
### Query
- NetworkId: `HUNGARY`
- From: `Location{POI, 47.4979930/19.0403590, name=Budapest}`
- Via: `null`
- To: `Location{POI, 47.4979930/19.0403590, name=Budapest}`
- Date: `Thu Sep 02 22:22:53 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/hu/journeys?from=19.040359%3B47.497993&to=19.040359%3B47.497993&datetime=20210902T222253&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:284)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:198)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
