### ISSUE TITLE
VVS: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)

### ISSUE THREAD

**Issue by njmdietrich** [schildbach/public-transport-enabler#399]
### Query
- NetworkId: `VVS`
- From: `Location{STATION, 5006118, 48.7833860/9.1802290, place=Stuttgart, name=Hauptbahnhof}`
- Via: `null`
- To: `Location{STATION, 5006056, 48.7763290/9.1730470, place=Stuttgart, name=Rotebühlplatz}`
- Date: `Fri Sep 03 17:13:05 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
This isn't related to public-transport-enabler.
