### ISSUE TITLE
VVM: migrate to DEFAS endpoint

### ISSUE THREAD

**Issue by alexander-albers** [schildbach/public-transport-enabler#400]
It seems like the [currently used](https://github.com/schildbach/public-transport-enabler/blob/master/src/de/schildbach/pte/VvmProvider.java) endpoint is no longer available. The VVM (iOS) app uses `https://mobile.defas-fgi.de/vvmapp/`, which seems to work just fine and does not use different station ids.

The new endpoint uses the mobile efa API. I already implemented the necessary changes in my [Swift port](https://github.com/alexander-albers/tripkit/commit/c4cf3ed838032943f7b52fe235afffcf304a0342) of the PTE and changes are very minor (I basically copied all overridden API method from the Bayern provider). If you want, I could submit a PR for PTE as well.

**Comment by schildbach** [comment]
Good hint! Fixed via 1105bb20a60681cdc578ef87eedbccb0909b6afc.

**Comment by alexander-albers** [comment]
@schildbach I'm really sorry, I think I messed this one up. I confused VVM Mittelschwaben (https://www.vvm-online.de/home) with VVM Mainfranken (https://www.vvm-info.de/) and only looked up the endpoint for the latter. The name of the defas url path did not help. The worst part is that this already happened to me once before..

Unfortunately, while the current app of VVM Mittelschwaben is operated by eos.uptrade, they don't use the efa API.

Now the next confusing part is that both providers use https://www.bayern-fahrplan.de in their website for all trip requests [[1]](https://www.vvm-info.de/echtzeit_fahrplanauskunft/) [[2]](https://www.vvm-online.de/fahrplansuche). So I guess both providers are connected with DEFAS, which probably also explains why in my testing I didn't even had to update the stop ids.

Any idea how to move forward with this?

**Comment by alexander-albers** [comment]
Fyi, mobilitaetsverbund.de uses the bayern-fahrplan.de endpoint on their website as well: http://mobilitaetsverbund.de/Fahrplanauskunft,11.html

**Comment by schildbach** [comment]
So I take it this PR doesn't cause any harm. Am I correct?

**Comment by alexander-albers** [comment]
Yes, that's true. Since both providers use DEFAS, there shouldn't be any problems with just switching to VVM Mainfranken which is probably also better known than VVM Mittelschwaben. Even if there is any issue for VVM Mittelschwaben users, they could still fall back to the Bayern provider, which is used on the official website anyways.
