### ISSUE TITLE
Finland Turku Trip Planner Has Issues

### ISSUE THREAD

**Issue by blindm0use** [schildbach/public-transport-enabler#403]
### Query
- NetworkId: `FINLAND`
- From: `Location{ADDRESS, 60.4750280/22.3052640, place=Turku, name=Ritzinkuja}`
- Via: `null`
- To: `Location{ADDRESS, 60.4135100/22.3047800, place=Turku, name=Varsinais-Suomenkatu 3}`
- Date: `Sun Sep 19 14:35:30 GMT+03:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
There have been problems lately with Transportr and Turku town in Finland. Instead of navitia, the app can fetch data from opas.matka.fi, as an alternative for Finland, which in comparison works without problems.

Additionally, the app is not able to search for a specific house/street number.

Can you be so kind to look into this issue?

Thanks in advance!

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
