### ISSUE TITLE
SNCB: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)

### ISSUE THREAD

**Issue by JohanvdS** [schildbach/public-transport-enabler#404]
### Query
- NetworkId: `SNCB`
- From: `Location{STATION, 8895836, 50.8825320/4.0952880, name=Liedekerke, products=[HIGH_SPEED_TRAIN, BUS]}`
- Via: `null`
- To: `Location{STATION, 8833001, 50.8822800/4.7158670, name=Leuven / Louvain, products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, BUS]}`
- Date: `Tue Sep 21 13:00:15 GMT+02:00 2021`
- Departure: `false`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
This seems like a database issue in Transportr. Please report there. Nothing we can do.
