### ISSUE TITLE
SPAIN: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by S1e2b3** [schildbach/public-transport-enabler#408]
Es un mapa de capital funciona estupendamente , lo que pasa que tienes que especificar la salida y llegada en el mismo mapa,el coge sus propias coordenadas, es mas um mapa de capital, no puebol cercanos y es un estupendo buscador de calles dentro una capital si no yr da error porque es muy extensa su busqueda , 
coge toda España y hay pueblos y calles con el mismo nombre  no se si es OpenStreed que bajas el software de un estado por ejemplo Francia,España,Alemania etc por lo demas es un estupendo callejero , gracias por su atencion , escribo muy mal el ingles aunque lo hablo y leo perfectamente ### Query
- NetworkId: `SPAIN`
- From: `Location{ADDRESS, 39.5705000/2.8579300, place=Illes Balears, name=Algaida}`
- Via: `null`
- To: `Location{ADDRESS, 39.5506300/2.8589730, place=Illes Balears, name=camí de sa Comuna}`
- Date: `Thu Sep 30 18:04:43 GMT+02:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
