### ISSUE TITLE
AUSTRALIA: java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination

### ISSUE THREAD

**Issue by dissociativity** [schildbach/public-transport-enabler#417]
### Query
- NetworkId: `AUSTRALIA`
- From: `Location{ADDRESS, -37.7746080/144.9588910, place=Melbourne, name=Union Street City of Moreland}`
- Via: `null`
- To: `Location{POI, -37.8114240/144.9638460, place=Melbourne, name=Melbourne Central}`
- Date: `Fri Nov 05 16:07:00 GMT+11:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error id: no_origin_nor_destination
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1065)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
Using microG installer from magisk repo, location services work fine for herewego maps, mozzila location provider + nominatim
This error is presented trying to go to Melbourne, Central station in Victoria, Australia

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
