### ISSUE TITLE
BVG: de.schildbach.pte.exception.BlockedException: https://bvg.hafas.cloud/bin/mgate.exe

### ISSUE THREAD

**Issue by besendorf** [schildbach/public-transport-enabler#419]
### Query
- NetworkId: `BVG`
- From: `Location{STATION, 900007102, 52.5486380/13.3883720, place=Berlin, name=S+U Gesundbrunnen Bhf, products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, BUS]}`
- Via: `null`
- To: `Location{STATION, 900078201, 52.4693890/13.4427210, place=Berlin, name=S+U Neukölln, products=[SUBURBAN_TRAIN, SUBWAY, BUS]}`
- Date: `Mon Nov 08 09:21:21 GMT+01:00 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
de.schildbach.pte.exception.BlockedException: https://bvg.hafas.cloud/bin/mgate.exe
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:284)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonTripSearch(AbstractHafasClientInterfaceProvider.java:583)
```

### Additional information
All Navigation in Transportr broken since today

**Comment by besendorf** [comment]
Sorry already reported.

**Comment by derhuerst** [comment]
duplicate of #418
