### ISSUE TITLE
ONTARIO: INVALID_DATE

### ISSUE THREAD

**Issue by OpenWarp** [schildbach/public-transport-enabler#420]
### Query
- NetworkId: `ONTARIO`
- From: `Location{ADDRESS, 43.7471290/-79.4786750, place=North York, name=Carl Hall Road 37}`
- Via: `null`
- To: `Location{ADDRESS, 43.6753380/-79.4331460, place=Old Toronto, name=Regal Road 2}`
- Date: `Thu Nov 11 11:59:29 EST 2021`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
The search date is currently not supported by the data provider. Please try another date.
```

### Additional information
Public transportation information is available on TTC.ca web site. The trip planner is Triplinx. In this case, the URL is https://www.triplinx.ca/en/trip-planner/4/JourneyPlanner?partnerCode=TTC
They have a Triplinx mobile app referenced on their web site. So there is probably an API. And then there are similar apps for Toronto TTC listed on Play Store.

For now, I have to use OsmAnd~ app to calculate the route. It does a good job despite being in beta. Not sure whether it make sense to allow to plan the trip in Transportr search directions menue based on intervals without the need to specify the time. This would resolve the issue of the timetable not being available.

**Comment by jtracey** [comment]
To be clear, TTC, as well as GO, GRT, and MiWay, were all supported until recently, and seem like they should still be: https://navitia.opendatasoft.com/explore/dataset/ca-on/information/
It's not clear to me what is going wrong.

**Comment by jtracey** [comment]
I think this has been resolved.

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
