### ISSUE TITLE
No calendar installed :( 

### ISSUE THREAD

**Issue by joeyboon** [schildbach/public-transport-enabler#430]
After updating to Transportr 2.1.4 I cant add trips to my calendar any more. Whenever I try to do so it claims there is no calendar app installed. It could also have happened because I updated to Android 12 (Graphene OS on Pixel 4A). My default calendar app is Etar. What other info do you need to look into this? Let me know and keep up the good work! :)

**Comment by schildbach** [comment]
Please report this issue to Transportr.
