### ISSUE TITLE
NEGENTWEE: de.schildbach.pte.exception.NotFoundException: https://api.9292.nl/0.1/journeys?lang=en-GB&from=station-delft&to=station-gouda&searchType=departure&dateTime=2022-01-23T1447&sequence=1&realtime=true&before=1&after=5&interchangeTime=standard&byBus=true&byTrain=true&bySubway=true&byTram=true&byFerry=true

### ISSUE THREAD

**Issue by Apanatshka** [schildbach/public-transport-enabler#443]
### Query
- NetworkId: `NEGENTWEE`
- From: `Location{STATION, station-delft, 52.0065830/4.3563920, place=Delft, name=Station Delft}`
- Via: `null`
- To: `Location{STATION, station-gouda, 52.0172160/4.7061650, place=Gouda, name=Station Gouda}`
- Date: `Sun Jan 23 14:47:06 GMT+01:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
de.schildbach.pte.exception.NotFoundException: https://api.9292.nl/0.1/journeys?lang=en-GB&from=station-delft&to=station-gouda&searchType=departure&dateTime=2022-01-23T1447&sequence=1&realtime=true&before=1&after=5&interchangeTime=standard&byBus=true&byTrain=true&bySubway=true&byTram=true&byFerry=true
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:286)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:198)
```

### Additional information
I get this all the time now, no matter the start or end I put in, I've tried multiple information sources too.

**Comment by Muspah** [comment]
See #440, RIG changed it's API endpoints.

**Comment by Apanatshka** [comment]
Ah, sorry for the dup
