### ISSUE TITLE
SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)

### ISSUE THREAD

**Issue by manulari** [schildbach/public-transport-enabler#458]
### Query
- NetworkId: `OEBB`
- From: `Location{STATION, 1232415, 48.3363640/16.2987730, name=Kritzendorf Bahnhof, products=[HIGH_SPEED_TRAIN, SUBURBAN_TRAIN, BUS]}`
- Via: `null`
- To: `Location{STATION, 324286, 48.3086690/16.2579440, name=Maria Gugging IST Austria, products=[BUS]}`
- Date: `Mon Mar 21 09:09:18 GMT+01:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
```

### Additional information
This is currently reproducible.
A query for the similarly named destination "Maria Gugging I.S.T. Austria" (with dots) works, and queries to other destinations also work.
(In the real world these must be the same destination.)

**Comment by schildbach** [comment]
Public-transport-enabler doesn't use SQLite. The error must be in the app you're using.
