### ISSUE TITLE
SNCB: NO_TRIPS

### ISSUE THREAD

**Issue by huguesdk** [schildbach/public-transport-enabler#461]
### Query
- NetworkId: `SNCB`
- From: `Location{STATION, 8814001, 50.8357070/4.3365310, name=Bruxelles-Midi, products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBWAY, TRAM, BUS]}`
- Via: `null`
- To: `Location{STATION, 8814159, 50.7676320/4.3539520, name=Holleken, products=[]}`
- Date: `Wed Mar 23 22:23:32 GMT+01:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
Aucune correspondance n’a été trouvée :(
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Won't fix. `SncbProvider` has been removed, see #502.
