### ISSUE TITLE
SNCB: NO_TRIPS

### ISSUE THREAD

**Issue by JohanvdS** [schildbach/public-transport-enabler#462]
### Query
- NetworkId: `SNCB`
- From: `Location{ADDRESS, 50.9195200/4.1122020, place=Vlaams-Brabant, name=De Mattein}`
- Via: `null`
- To: `Location{STATION, 8812005, 50.8596630/4.3608470, place=Brussel, name=Noord, products=[HIGH_SPEED_TRAIN, TRAM, BUS]}`
- Date: `Sat Apr 02 09:08:47 GMT+02:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
Geen verbindingen gevonden :(
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Won't fix. `SncbProvider` has been removed, see #502.
