### ISSUE TITLE
FRANCESOUTHEAST: de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-se/journeys?from=4.91453%3B45.749577&to=4.872263%3B45.778249&datetime=20220404T145254&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.344

### ISSUE THREAD

**Issue by bananasplouf** [schildbach/public-transport-enabler#463]
### Query
- NetworkId: `FRANCESOUTHEAST`
- From: `Location{ADDRESS, 45.7495770/4.9145300, place=Villeurbanne, name=Rue du Luxembourg 15}`
- Via: `null`
- To: `Location{ADDRESS, 45.7782490/4.8722630, place=Villeurbanne, name=Rue Marguerite 29}`
- Date: `Mon Apr 04 14:52:54 GMT+02:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-se/journeys?from=4.91453%3B45.749577&to=4.872263%3B45.778249&datetime=20220404T145254&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.344
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:284)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:198)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
