### ISSUE TITLE
NS (Netherlands) stations lack location

### ISSUE THREAD

**Issue by TheLastProject** [schildbach/public-transport-enabler#47]
The NS (Netherlands) stations are returned without location.

See grote/Transportr#94.

**Comment by schildbach** [comment]
Yes, the NsProvider is in a horrible state. It's still scraping an HTML site for nearby stations.

**Comment by schildbach** [comment]
I think the way forward for this provider is to somehow use the JSON API at http://hafas.bene-system.com/bin/mgate.exe … however that API needs authorization.

**Comment by TheLastProject** [comment]
On http://openov.nl/ I found a reference to a Rest API called OVapi, with more info on https://github.com/skywave/KV78Turbo-OVAPI/wiki.

Unfortunately, the openov site seems to only be in Dutch and lack a lot of info about OVapi. The OVapi site itself has no useful info whatsoever. I am not sure how helpful the Wiki page is, or how reliable the API is.

**Comment by schildbach** [comment]
I'm closing this, as this is a server issue. If someone's got a solution, feel free to comment. If someone would like to implement that REST API, I'm happy to take a pull request or assist with implementation.
