### ISSUE TITLE
VVO: NO_TRIPS

### ISSUE THREAD

**Issue by FriederHannenheim** [schildbach/public-transport-enabler#472]
### Query
- NetworkId: `VVO`
- From: `Location{ADDRESS, 50.9455950/14.0736330, place=Sachsen, name=Weißig 14}`
- Via: `null`
- To: `Location{ADDRESS, streetID:1500002369::14612000:-1:Am Schillergarten:Dresden:Am Schillergarten::Am Schillergarten: 01277:ANY:DIVA_STREET:1537200:5369623:MRCV:VVO, 51.0513220/13.8089030, place=Dresden, name=Dresden, Am Schillergarten}`
- Date: `Thu May 26 15:00:21 GMT+02:00 2022`
- Departure: `false`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
No connections could be found :(
```

### Additional information
[Please modify this part]

**Comment by ialokim** [comment]
@schildbach the VVO base url has been fixed in Transportr since version 2.2.0, you may close this.
