### ISSUE TITLE
Add VMT Provider

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#48]
Is there any reason, why there is no VMT provider?

It seems to use normal HAFAS: http://vmt.hafas.de/bin/query.exe/dn

**Comment by schildbach** [comment]
The essential API endpoints are blocked.

**Comment by qbi** [comment]
I got in contact with VMT. They told me that they already had contact with @schildbach and provide a XML interface. However it seems that those data can't be integrated with the app. Maybe Andreas can tell more about it.

**Comment by schildbach** [comment]
My last contact was in June to Mr. Marx. He said they are working an a new system which bundles all the data for Thuringia. I don't know what kind of API this will be. Also apparenty the VMT doesn't want to unblock the current Hafas endpoints.
