### ISSUE TITLE
VVO: de.schildach.pte.exception.ParserException: cannot parse xml

### ISSUE THREAD

**Issue by killermoehre** [schildbach/public-transport-enabler#490]
Since a few days(?), VVO (Germany, Saxony) queries seem to have a different format. All data is actually in the result.

What I found out using the official APP is that now live-data is added.

**Comment by FriederHannenheim** [comment]
Please fix this

**Comment by ixfbc** [comment]
The error message has changed:
![pic](https://user-images.githubusercontent.com/125284284/224841266-08bccec1-3e7e-4ba1-b5fd-fed26d1247db.jpg)

**Comment by ialokim** [comment]
@schildbach the VVO base url has been fixed in Transportr since version 2.2.0, you may close this.
