### ISSUE TITLE
SNCB: java.lang.IllegalStateException: cannot handle type: CHKI

### ISSUE THREAD

**Issue by gargamel17** [schildbach/public-transport-enabler#492]
### Query
- NetworkId: `SNCB`
- From: `Location{STATION, 260976, 50.6948550/5.2500870, name=WAREMME Gare [TEC]}`
- Via: `null`
- To: `Location{STATION, 8813003, 50.8456490/4.3568020, name=Bruxelles-Central, products=[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBWAY, BUS]}`
- Date: `Fri Oct 28 19:13:09 GMT+02:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalStateException: cannot handle type: CHKI
de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonTripSearch(AbstractHafasClientInterfaceProvider.java:751)
de.schildbach.pte.AbstractHafasClientInterfaceProvider.queryTrips(AbstractHafasClientInterfaceProvider.java:214)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
```

### Additional information
[Please modify this part]

**Comment by derhuerst** [comment]
`CHKI` support has been added only recently: https://github.com/schildbach/public-transport-enabler/commit/889ceb5994d3797b1f7772595365ec9c5fd009bb

Could it be that @gargamel17 wasn't using the most up-to-date version of `public-transport-enabler`?

**Comment by gargamel17** [comment]
Hello, version I use is 2.1.4, available on F-Droid (IzzyOnDroid repo)

**Comment by schildbach** [comment]
Won't fix. `SncbProvider` has been removed, see #502.
