### ISSUE TITLE
Add polish transport provider "ZTM"

### ISSUE THREAD

**Issue by mimi89999** [schildbach/public-transport-enabler#50]
Would it be possible to add "ZTM" support?
They are in the list: https://maps.google.com/landing/transit/cities/index.html#Europe under Poland/Warsaw/ZTM Warszawa
Thanks in advance.

**Comment by grote** [comment]
That they are listed there is good. It means that they have their data available in GTFS format, so support for it could be added using Navitia, provided we can get the GTFS data added to the Navitia web service. I tried to explain the options here: http://transportr.grobox.de/#add_region
So maybe try to find the GTFS data for ZTM and get it added to Navitia.

Is the ZTM data not available within the current provider for Poland?

**Comment by mimi89999** [comment]
For Poland, I can see only "PKP" provider.

**Comment by schildbach** [comment]
I have a ZtmProvider on a private branch, they've got a Hafas API. However, there was a serious problem that kept me from using it. Can't remember the details, would need to try again.

**Comment by mimi89999** [comment]
Could you check what was the problem?

**Comment by schildbach** [comment]
I published the branch: https://github.com/schildbach/public-transport-enabler/commits/provider-ztm

The main issue is that departures can't be queried. If someone could talk to ZTM about that, it would be great!

Also it's missing types, but that's an issue on our side.

**Comment by mimi89999** [comment]
I built Transportr including https://github.com/schildbach/public-transport-enabler/commits/provider-ztm and when I tested it, I got this error:
java.lang.IllegalStateException: cannot normalize type '14'

**Comment by schildbach** [comment]
Yes, the line to product mapping is largely unfinished. But that's only a minor problem, if all else fails we could map any line to null (unknown product).

**Comment by mimi89999** [comment]
I changed https://github.com/mimi89999/public-transport-enabler/commit/8c7821e1e30e5b925f824cc84291ee6f3dad12ed to get readable addresses...

**Comment by mimi89999** [comment]
I found this contact form: http://ztm.waw.pl/?c=115&l=1 , but I don't think I'm capable of writing to them...

**Comment by grote** [comment]
Why are you not capable? Would you be able to write to them if you understood the nature of the problem with querying departures better?

**Comment by mimi89999** [comment]
Yes

**Comment by mimi89999** [comment]
There is also a contact form in english: https://secure.ztm.waw.pl/index.php?c=115&l=2

**Comment by mimi89999** [comment]
I wrote to them...

**Comment by mimi89999** [comment]
They replied that they needed more details.

**Comment by schildbach** [comment]
If they have an english speaking contact I'd be happy to email them.

**Comment by mimi89999** [comment]
https://secure.ztm.waw.pl/index.php?c=115&l=2

**Comment by schildbach** [comment]
*email*

**Comment by mimi89999** [comment]
There is no email. Only this contact form :-(

**Comment by mimi89999** [comment]
You could try: ztm@ztm.waw.pl

**Comment by schildbach** [comment]
I then never mind. What I meant is if we have a specific contact person there at ZTM we can work with, I'm happy to explain details. Someone who is able to configure their Hafas server.

**Comment by mimi89999** [comment]
I will write to them and ask.

**Comment by mimi89999** [comment]
The email address from which I got the reply was: ztm@ztm.waw.pl, so it seems that they don't use/give any other email address. They don't give any contact email on their website.  :disappointed:

**Comment by mimi89999** [comment]
@schildbach But since ZTM is in the list https://maps.google.com/landing/transit/cities/index.html#Europe , there should be GTFS data available for it. Did I understand something the wrong way?

**Comment by schildbach** [comment]
@mimi89999 PTE expects an API. GTFS is a data format.

**Comment by DroidFire** [comment]
@schildbach @grote I've recently found something called "Dbtimetable API" for ZTM: api.um.warszawa.pl unfortunately all the information are available only in Polish, but you can write to kontakt@um.warszawa.pl. I know that it is appropriate address for this site and it can be used by English speaking people.

**Comment by mimi89999** [comment]
Any news?

**Comment by Natsuyasumi** [comment]
I'm a bit late, but I provide a set of feeds with Warsaw data, avaible at [otp-pl.tk](http://otp-pl.tk), of that would help.

The ZTM doesn't have a GTFS feed, they have feed in their custom format, which Google than uses to create GTFS.

**Comment by mimi89999** [comment]
@schildbach Is that feed usable?

**Comment by Etua** [comment]
@MKuranowski Nativia [decided](https://groups.google.com/forum/#!topic/navitia/dygCiYIsY2I/discussion) to use your feed.

**Comment by Etua** [comment]
@schildbach I presume that now it will be possible to add not only Warsaw, but also other cities added by Nativia?

**Comment by grote** [comment]
@Etua this is true. However, I would not wait for @schildbach to do this work for you.

**Comment by mimi89999** [comment]
The data is on [Nativia](https://navitia.opendatasoft.com/explore/dataset/pl/information/) and [Google](https://maps.google.com/landing/transit/cities/index.html). Other sources are also available: https://mkuran.pl/feed/ztm/ and https://przyjazdy.pl/latest/warszawa.zip . Is there a simple HOWTO for people who are not familiar with the PTE lib and apps using it?

**Comment by mimi89999** [comment]
@grote The API sometimes returns the line number as type. It will be a nightmare to do the mapping.

**Comment by mimi89999** [comment]
I added it. https://gitlab.com/opentransitmap/public-transport-enabler/merge_requests/1/

**Comment by mimi89999** [comment]
Departures are still broken. The HTML interface is returned instead of a table. I wrote again to ZTM about it. Let's hope that they will do something about it.

**Comment by mimi89999** [comment]
ZTM replied that the official way of getting data are the zips that they provide, that I wrote about before and the API that @etua wrote about.

I'm not even sure that they are aware that their "wyszukiwarka" is exposing an API...

**Comment by MKuranowski** [comment]
@mimi89999 Well, it's like ZTM said: the *only* official way to download data from them is ftp://rozklady.ztm.waw.pl/ — that's the source for GTFS on [mkuran.pl](https://mkuran.pl/feed/ztm/) ([PRZYJAZDY.PL](https://przyjazdy.pl/gtfs) is just a reupload of mine data 😉). The HAFAS from http://wyszukiwarka.ztm.waw.pl/ is very wired and I'd recommend to forget about it.

On the other hand, [Warsaw Open Data project](https://api.um.warszawa.pl) has this [DBtimetable API (linked doc in Polish)](https://api.um.warszawa.pl/wcag/wizualizacja/dokumentacja.php?src=91f49cb2-9ffb-41bd-8e25-5204bb9da990), but it offers only timetables per-stop, so I'd assume it lacks crucial (from trip planning point of view) data.

**Comment by schildbach** [comment]
I just merged #207. Is this issue resolved?

**Comment by mimi89999** [comment]
Yes
