### ISSUE TITLE
PLNAVITIA: java.lang.IllegalArgumentException: Unhandled error message: The region pl doesn't exists

### ISSUE THREAD

**Issue by ghost** [schildbach/public-transport-enabler#503]
### Query
- NetworkId: `PLNAVITIA`
- From: `Location{POI, 52.2299710/21.0107790, place=Warszawa, name=Metro Centrum}`
- Via: `null`
- To: `Location{ADDRESS, 52.2714020/21.0144750, place=Warschau, name=Jagiellońska Akademia Leona Koźmińskiego, PL-14, Pelcowizna}`
- Date: `Wed Dec 14 14:48:39 GMT+01:00 2022`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.lang.IllegalArgumentException: Unhandled error message: The region pl doesn't exists
de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1061)
de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:110)
de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)
```

### Additional information
I am using an app called [Transportr](https://transportr.app/) in Poland, it has suddenly started throwing errors at my without any changes to my configuration or circumstance. I am using a FairPhone 4 with CalyxOS (version 4.4.0).
![signal-2022-12-14-144654](https://user-images.githubusercontent.com/76809077/207614410-8d243221-5827-4922-81ec-0d82bd0fe8c6.png)

**Comment by aceryz** [comment]
I'm experiencing the exact same issue, also on Transportr. Samsung S7 Edge, LineageOS 19 (Android 12).

**Comment by KhazAkar** [comment]
It was removed for no apparent reason for example in Oeffi/PTE. It can be checked on gitlab repository.

@schildbach what was the reasoning of this? It's only FOSS app known to me which supports Poland in any way in terms of public transport, both PKP and providers like ZTM.

**Comment by schildbach** [comment]
It's the `PlProvider` (for PKP) that was removed via 4faef721bdf62a24152453360b94e583fcd21d93, because the Hafas backend ceased to exist.

This issue is about the Navitia based provider.

**Comment by KhazAkar** [comment]
Thanks for quick response and I'm sorry :)
Also, I can propose using bilkom for polish railways :)

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
