### ISSUE TITLE
GTFS data for belgium

### ISSUE THREAD

**Issue by tias** [schildbach/public-transport-enabler#52]
Please find GTFS data for Belgium here:
http://gtfs.irail.be/

You can find the people maintaining that here:
https://github.com/iRail

**Comment by schildbach** [comment]
Public transport enabler cannot deal with raw data. It currently needs a routing service, and a service for station boards, etc. The main providers implemented are Navitia, Hafas and EFA.

**Comment by grote** [comment]
This data seems to have been added to Navitia already. So adding it to PTE is just a question of adding a Navitia Provider for Belgium.
