### ISSUE TITLE
VVO: java.io.IOException: unexpected end of stream on Connection{efaproxy.fahrinfo.uptrade.de:80, proxy=DIRECT hostAddress=efaproxy.fahrinfo.uptrade.de/185.5.24.52:80 cipherSuite=none protocol=http/1.1}

### ISSUE THREAD

**Issue by chisade** [schildbach/public-transport-enabler#524]
### Query
- NetworkId: `VVO`
- From: `Location{STATION, 33000019, 51.0577870/13.7412330, place=Dresden, name=Neustädter Markt}`
- Via: `null`
- To: `Location{STATION, 33000037, 51.0508360/13.7335160, place=Dresden, name=Postplatz}`
- Date: `Tue Apr 04 07:40:00 GMT+02:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
java.io.IOException: unexpected end of stream on Connection{efaproxy.fahrinfo.uptrade.de:80, proxy=DIRECT hostAddress=efaproxy.fahrinfo.uptrade.de/185.5.24.52:80 cipherSuite=none protocol=http/1.1}
okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
Cause: okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:236)
okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
```

### Additional information
Every search in the area of Dresden (VVO) currently fails. It doesn't really matter which one. I didn't test if other cities / locations are effected as well.

Happens under GrapheneOS.

Let me know if I can provide more debugging information.

**Comment by ialokim** [comment]
@schildbach the VVO base url has been fixed in Transportr since version 2.2.0, you may close this.
