### ISSUE TITLE
FRANCENORTHWEST: de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-nw/journeys?from=-1.559285%3B47.254863&to=-1.63126%3B47.223659&datetime=20230505T123559&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.344

### ISSUE THREAD

**Issue by nils-van-zuijlen** [schildbach/public-transport-enabler#530]
### Query
- NetworkId: `FRANCENORTHWEST`
- From: `Location{ADDRESS, 47.2548630/-1.5592850, place=Nantes, name=Avenue de l'Alverne}`
- Via: `null`
- To: `Location{POI, 47.2236590/-1.6312600, place=Saint-Herblain, name=Atlantis}`
- Date: `Fri May 05 12:35:59 GMT+02:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-nw/journeys?from=-1.559285%3B47.254863&to=-1.63126%3B47.223659&datetime=20230505T123559&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.344
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:284)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:205)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:198)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Thanks a lot for your report. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this report. Sorry for the inconvenience and thanks again.
