### ISSUE TITLE
DB: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)

### ISSUE THREAD

**Issue by ChrisPHL** [schildbach/public-transport-enabler#546]
### Query
- NetworkId: `DB`
- From: `Location{STATION, 8004057, 53.6244580/10.6830770, name=Mölln(Lauenb), products=[REGIONAL_TRAIN, BUS]}`
- Via: `null`
- To: `Location{STATION, 8004253, 49.6062350/7.1729420, name=Neubrücke(Nahe), products=[REGIONAL_TRAIN, BUS]}`
- Date: `Fri Oct 13 15:01:36 GMT+02:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
This is obviously an issue in Transportr, please take it to there.
