### ISSUE TITLE
VBB: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)

### ISSUE THREAD

**Issue by woffs** [schildbach/public-transport-enabler#550]
### Query
- NetworkId: `VBB`
- From: `Location{STATION, 900182503, 52.4556080/13.6190260, place=Berlin, name=Ahornallee, products=[TRAM, BUS]}`
- Via: `null`
- To: `Location{STATION, 900181003, 52.4575140/13.5438940, place=Berlin, name=Freizeit- und Erholungszentrum, products=[TRAM, BUS]}`
- Date: `Mon Dec 18 09:08:13 GMT+01:00 2023`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
```

### Additional information
- probably the dash in the destination name triggers an exception
- app is transportr

**Comment by schildbach** [comment]
This is obviously an issue in Transportr, please take it to there.

**Comment by woffs** [comment]
as expected. thanks! :-)
