### ISSUE TITLE
MVV provider broken

### ISSUE THREAD

**Issue by M00NJ** [schildbach/public-transport-enabler#567]
Unfortunately two weeks ago the MVV provider (Munich) started giving this Error message: 'Could not find the 'from' location. Please try another one.' I've tried about ten diffrent starting locations but I doesn't matter what you enter, the issue persists. I'm using the latest version of Transportr. Screenshot:![signal-2024-04-12-14-46-24-892.jpg](https://github.com/schildbach/public-transport-enabler/assets/82398591/de7aa859-1f71-490d-841c-2ab316a4a327)

**Comment by M00NJ** [comment]
I did't some tests with Öffi and it's broken there as well. It displays diffrent errors though depending on what you enter.

**Comment by johan12345** [comment]
The MVV provider is using an old endpoint, which is apparently broken now. PR #414, which switches to the new endpoint used by the current MVV website, has already been open for a long time, and should fix it...
