### ISSUE TITLE
dosent work anymore on HVV since yesterday (in german)

### ISSUE THREAD

**Issue by nanderer** [schildbach/public-transport-enabler#589]
Hi,

seit Gestern hab ich bemerkt das es mit Verbindungen in Hamburg nicht mehr klappt:
egal was ich eingebe, ich bekomme immer diese Fehlermeldung:
![image](https://github.com/user-attachments/assets/d4d0635e-6c6b-4e82-afa9-c529e8eb7b37)
schade, ich hoffe das lässt sich reparieren...

Danke und Gruß aus HH

**Comment by nanderer** [comment]
translation:
  
    
      
          
Hi,
Since yesterday I have noticed that it no longer works with connections in Hamburg:

no matter what I enter, I always get this error message:

( Unknown Start- or Endpoint )

too bad, I hope this can be fixed...
Thanks and greetings from HH

**Comment by schildbach** [comment]
Please try clearing your query history and then try querying again. It seems the station ID of "Hamburg, Hbf" has changed.

Such issues are best discussed in the Matrix room: https://matrix.to/#/#öffi:schildbach.de
