### ISSUE TITLE
PARIS: de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-idf/journeys?from=stop_area%3AIDFM%3A71285&to=stop_area%3AIDFM%3A71139&datetime=20241110T082322&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12

### ISSUE THREAD

**Issue by BuzzAl** [schildbach/public-transport-enabler#601]
### Query
- NetworkId: `PARIS`
- From: `Location{STATION, stop_area:IDFM:71285, 48.8634460/2.2872440, place=Quartier de Chaillot, name=Trocadéro}`
- Via: `null`
- To: `Location{STATION, stop_area:IDFM:71139, 48.8406720/2.3193430, place=Quartier Necker, name=Gare Montparnasse}`
- Date: `Sun Nov 10 08:23:22 GMT+01:00 2024`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-idf/journeys?from=stop_area%3AIDFM%3A71285&to=stop_area%3AIDFM%3A71139&datetime=20241110T082322&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:294)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:215)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:208)
```

### Additional information
[Please modify this part]
It seems that the application doesn't work anymore. 

Best regards

**Comment by TheFighter137** [comment]
I just opened a very similar issue in the French Northwest region. Do you also use the Transportr app ?
