### ISSUE TITLE
Error when attempting to calculate any route with Transportr

### ISSUE THREAD

**Issue by TheFighter137** [schildbach/public-transport-enabler#602]
### Query
- NetworkId: `FRANCENORTHWEST`
- From: `Location{ADDRESS, 49.4674270/1.0996450, place=Seine-Maritime, name=18 18 Sente des Bulins}`
- Via: `null`
- To: `Location{ADDRESS, 49.4463920/1.0711800, place=Quartier Pasteur, name=134 134 Avenue Mont Riboudet}`
- Date: `Sun Nov 10 10:46:56 GMT+01:00 2024`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-nw/journeys?from=1.099645%3B49.467427&to=1.07118%3B49.446392&datetime=20241110T104656&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.344
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:294)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:215)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:208)
```

### Additional information
This error appears every time I need to calculate a route in the French Northwest region.

**Comment by schildbach** [comment]
Navitia has been shut down.
