### ISSUE TITLE
VMV NotFoundException

### ISSUE THREAD

**Issue by nordisch-dev** [schildbach/public-transport-enabler#603]
Live Test
![image](https://github.com/user-attachments/assets/81767000-4a3f-45ff-a9e1-1f8ad545195e)

I get no stations/data from the VMV API in the Transportr App
![signal-2024-11-13-184432](https://github.com/user-attachments/assets/a9ef9e35-e981-4e3a-ae71-b3ab6e74c653)

**Comment by schildbach** [comment]
Fixed via ec0d27033bbe3f02aa20bdd50dfced6dd0391f84.
