### ISSUE TITLE
FRANCESOUTHWEST: de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-sw/journeys?from=-1.023212%3B46.120645&to=-1.023121%3B46.120624&datetime=20241121T213943&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12

### ISSUE THREAD

**Issue by JibiLine** [schildbach/public-transport-enabler#605]
### Query
- NetworkId: `FRANCESOUTHWEST`
- From: `Location{ADDRESS, 46.1206450/-1.0232120, place=La Jarrie, name=Rue du Fief Boutin 2}`
- Via: `null`
- To: `Location{ADDRESS, 46.1206240/-1.0231210, place=Charente-Maritime, name=2 Rue du Fief Boutin 2}`
- Date: `Thu Nov 21 21:39:43 GMT+01:00 2024`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-sw/journeys?from=-1.023212%3B46.120645&to=-1.023121%3B46.120624&datetime=20241121T213943&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:294)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:215)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:208)
```

### Additional information
[Please modify this part]

**Comment by JibiLine** [comment]
The chosen route is irrelevant, as it simply doesn't work regardless of the path taken.

**Comment by schildbach** [comment]
Navitia has shut down.

**Comment by wargreen** [comment]
> Navitia has shut down.

HUh !?
What do you think about the future of pte and transportr with this announce ?

**Comment by schildbach** [comment]
> What do you think about the future of pte and transportr with this announce ?

PTE still supports Hafas, EFA and some proprietary APIs. Also, PTE could support Transitous if someone takes the effort to implement and maintain.
