### ISSUE TITLE
PARIS: de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-idf/journeys?from=stop_area%3AIDFM%3A64883&to=stop_area%3AIDFM%3A65048&datetime=20241203T222619&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12

### ISSUE THREAD

**Issue by baba78300** [schildbach/public-transport-enabler#608]
### Query
- NetworkId: `PARIS`
- From: `Location{STATION, stop_area:IDFM:64883, 48.9329250/2.0406470, place=Poissy, name=Poissy}`
- Via: `null`
- To: `Location{STATION, stop_area:IDFM:65048, 48.9457380/2.1443240, place=Maisons-Laffitte, name=Maisons-laffitte}`
- Date: `Tue Dec 03 22:26:19 GMT+01:00 2024`
- Departure: `true`
- Products: `[HIGH_SPEED_TRAIN, REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `NORMAL`

### Error
```
de.schildbach.pte.exception.BlockedException: https://api.navitia.io/v1/coverage/fr-idf/journeys?from=stop_area%3AIDFM%3A64883&to=stop_area%3AIDFM%3A65048&datetime=20241203T222619&datetime_represents=departure&min_nb_journeys=6&depth=0&walking_speed=1.12
de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:294)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:215)
de.schildbach.pte.util.HttpClient.get(HttpClient.java:208)
```

### Additional information
[Please modify this part]

**Comment by schildbach** [comment]
Navitia has closed down.
