### ISSUE TITLE
DB: UNRESOLVABLE_ADDRESS

### ISSUE THREAD

**Issue by timhorn1** [schildbach/public-transport-enabler#609]
### Query
- NetworkId: `DB`
- From: `Location{STATION, 638739, 52.5042310/9.4560590, place=Neustadt am Rübenberge, name=Bahnhof/ZOB, products=[REGIONAL_TRAIN, SUBURBAN_TRAIN, BUS]}`
- Via: `null`
- To: `Location{ADDRESS, A=2@O=Neustadt am Rübenberge, Rundeel 3@H=3@X=9457533@Y=52505525@U=103@L=980923098@B=1@p=1548669839@, 52.5055250/9.4575330, place=Neustadt am Rübenberge, name=Rundeel 3}`
- Date: `Thu Dec 05 11:05:54 GMT+01:00 2024`
- Departure: `true`
- Products: `[REGIONAL_TRAIN, SUBURBAN_TRAIN, SUBWAY, TRAM, BUS, FERRY, CABLECAR, ON_DEMAND]`
- Optimize for: `LEAST_DURATION`
- Walk Speed: `FAST`

### Error
```
Konnte die eingegebene Adresse nicht finden. Bitte versuche es mit einer anderen.
```

### Additional information
[Please modify this part]

**Comment by traines-source** [comment]
Probably same as #610, the legacy HAFAS API has been increasingly unreliable in the past couple of weeks, see https://github.com/public-transport/hafas-client/issues/331#issuecomment-2529430123

**Comment by schildbach** [comment]
Yes, let's continue discussion in #610.
