### ISSUE TITLE
Switzerland Zurich ZVV network stopped working

### ISSUE THREAD

**Issue by tomgagdotnet** [schildbach/public-transport-enabler#612]
Transportr was working great with the zvv.ch local transport network until a few weeks ago. Now it does not:

![image](https://github.com/user-attachments/assets/094bf6b7-6fde-411c-9b6e-0a64b75cbdec)

Thanks a lot!

**Comment by derhuerst** [comment]
This is a duplicate of https://github.com/schildbach/public-transport-enabler/issues/606.

**Comment by schildbach** [comment]
Fixed via 81b1122204481bc980b091961244ecdb1a86aec0.
