### ISSUE TITLE
ZDiTM Szczecin

### ISSUE THREAD

**Issue by gjedeer** [schildbach/public-transport-enabler#75]
GTFS seems up to date: http://zditm.szczecin.pl/rozklady/GTFS/latest/

This is a public bus provider in Szczecin, Poland. Is the feed enough or do I need to ask them about anything else?

Website: http://zditm.szczecin.pl/
Logo: will be provided once you confirm it can be added.

**Comment by grote** [comment]
I've seen you requested this data to be added to Navitia's service. Until that has happened or there's not another supported service (like running your own Navitia server, they offering EFA, HAFAS interfaces) there's not much to do here.

**Comment by gjedeer** [comment]
OK, I'll reopen this issue when it's ready to be implemented. Thanks for answering.
